2023-02-13 update
Cumulative updates as of February 13 , 2023

diff --git a/ftk/install_igpsftk b/ftk/install_igpsftk
--- a/ftk/install_igpsftk
+++ b/ftk/install_igpsftk
@@ -29,7 +29,6 @@ set MK_CMD = "make -f Makefile.${arch}"
 set UNIMAKE_CMD = ${TARGETDIR}/unimake_igpsftk
 #set FC_CMD = ifort #Fortran Compiler
 #set FC_CMD = gfortran
-set FC_CMD = gftn
 
 #Test compiler used.
 cd $TARGETDIR
@@ -38,7 +37,7 @@ if( $status != 0 ) then
   echo "Failure in ${UNIMAKE_CMD} for testing compiler in lib --  terminated"   
   exit 1
 endif
-#set FC_CMD = `cat lib/Makefile.${arch} | awk '{if(substr($1,1,1)!="#"){print $0}}' | grep FTN | grep '=' | tail -1 | awk -F= '{print $2}' | awk '{print $1}'`
+set FC_CMD = `cat lib/Makefile.${arch} | awk '{if(substr($1,1,1)!="#"){print $0}}' | grep FTN | grep '=' | tail -1 | awk -F= '{print $2}' | awk '{print $1}'`
 echo Using Fortran Compiler: $FC_CMD
 #${UNIMAKE_CMD} -m lib -c ${FC_CMD} -e ${arch} 
 #exit
@@ -113,6 +112,32 @@ foreach PROG ( $PROGS )
     touch tmp.o; \rm -f *.o  
     echo Made ${PROG} 
 end
+
+echo ' '
+echo +++++++++++++++++++++++++++++++++++
+echo "SAR libraries & programs"
+echo +++++++++++++++++++++++++++++++++++
+echo " "
+
+set PROGS = "util overlap profile"
+#set PROGS = ""
+foreach PROG ($PROGS)
+    cd $TARGETDIR/sar
+    ${UNIMAKE_CMD} -m ${PROG} -c ${FC_CMD} -e ${arch} 
+    if( $status != 0 ) then
+	echo "Failure in ${UNIMAKE_CMD} for ${PKG}/${PROG} -- ${INST_PROG} terminated"   
+	exit 1
+    endif   
+    cd ${PROG}; ${MK_CMD}
+    if( $status != 0 ) then
+	echo "Failure in ${UNIMAKE_CMD} for ${PKG}/${PROG} -- ${INST_PROG} terminated"   
+	exit 1
+    endif
+    touch tmp.o; \rm -f *.o  
+    echo Made ${PROG} 
+end
+
+
 
 echo ' '
 echo +++++++++++++++++++++++++++++++++++
@@ -227,7 +252,7 @@ echo Making the tools programs
 echo ++++++++++++++++++++++++++++++++++
 echo " "
 set PROGS = "rewindstdin xyzneu u2l xyz2wgs84 td2rnx rnxdc newpsf met2wfile llhxyz geoxyz hello fcomb fcf"
-set PROGS = "hello rnxdc newpsf"
+set PROGS = "hello llhxyz newpsf rnxdc"
 foreach PROG (${PROGS})
     cd $TARGETDIR/tools
     ${UNIMAKE_CMD} -m ${PROG} -c ${FC_CMD} -e ${arch} 
diff --git a/sh/cron_esa_s1_get_orb b/sh/cron_esa_s1_get_orb
--- a/sh/cron_esa_s1_get_orb
+++ b/sh/cron_esa_s1_get_orb
@@ -37,8 +37,27 @@ if [ $? -ne 0 ]; then
 fi
 pwd
 
-rm -f index.html
-wget --no-check-certificate https://qc.sentinel1.eo.esa.int/aux_poeorb/
-grep EOF index.html | awk -F\" '{print " https://qc.sentinel1.eo.esa.int/aux_poeorb/"$2}' > eof.list
+page=1
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -page)
+      page=$2
+      ;;
+    *)
+      echo "[]ERROR: invalide option ($1)!!"
+      exit 1
+      ;;
+  esac
+  shift 2
+done
+echo page is $page
+
+ofile=index.html
+rm -f $ofile
+wget --no-check-certificate -O $ofile https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=${page}
+#wget --no-check-certificate https://qc.sentinel1.eo.esa.int/aux_poeorb/page=2
+#grep EOF index.html | awk -F\" '{print " https://qc.sentinel1.eo.esa.int/aux_poeorb/"$2}' > eof.list
+grep EOF $ofile | awk -F\" '{print " "$2}' > eof.list
 sh_esa_s1_get_orb eof.list
 
diff --git a/sh/cron_esa_s1_get_resorb b/sh/cron_esa_s1_get_resorb
--- a/sh/cron_esa_s1_get_resorb
+++ b/sh/cron_esa_s1_get_resorb
@@ -29,16 +29,73 @@ if [ "$esa_data" = "" ]; then
     fi
 fi
 
-path=${esa_data}/aux_resorb/
+ndays=3
+orb_type=res
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -ndays)
+      ndays=$2
+      ;;
+    -orb_type)
+      orb_type=$2
+      ;;
+    *)
+      echo "[]ERROR: invalid option ($1)!!"
+      exit 2
+      ;;
+  esac
+  shift 2
+done
+
+if [ "$orb_type" != "poe" -a  "$orb_type" != "res" -a  "$orb_type" != "pre" ]; then
+  echo "[]ERROR: invalid orbit type ($orb_type)!!"
+  exit 1
+fi 
+
+path=${esa_data}/aux_${orb_type}orb/
+if [ ! -d $path ]; then
+  echo "mkdir -p $path"
+  mkdir -p $path
+fi
 cd $path
 if [ $? -ne 0 ]; then
   ehco "Error!"
   exit 1
 fi
 pwd
+oldpath=`pwd`
 
-rm -f index.html
-wget --no-check-certificate https://qc.sentinel1.eo.esa.int/aux_resorb/
-grep EOF index.html | awk -F\" '{print " https://qc.sentinel1.eo.esa.int/aux_resorb/"$2}' > reseof.list
-sh_esa_s1_get_resorb reseof.list
 
+ORB_TYPE=`echo $orb_type | awk '{print toupper($1)}'`
+
+di=0
+while [ $di -lt $ndays ]; do
+  pwd
+  cd $oldpath
+  pwd 
+
+  year=`date -u +%Y -d "-$di days"`
+  mon=`date -u +%m -d "-$di days"`
+  day=`date -u +%d -d "-$di days"`
+  rm -f index.html
+#wget --no-check-certificate https://qc.sentinel1.eo.esa.int/aux_resorb/
+  url="http://aux.sentinel1.eo.esa.int/${ORB_TYPE}ORB/${year}/${mon}/${day}/"
+  wget --no-check-certificate $url
+
+#grep EOF index.html | awk -F\" '{print " https://qc.sentinel1.eo.esa.int/aux_resorb/"$2}' > reseof.list
+  if [ ! -s index.html ]; then
+    nl=0
+  else
+    grep EOF index.html | awk -F\" '{print " "url$2}' url=$url> reseof.list
+    nl=`cat reseof.list | wc -l`
+  fi
+  echo "nl $nl"
+  if [ $nl -ge 1 ]; then
+    cat reseof.list
+    echo sh_esa_s1_get_resorb reseof.list
+    echo sh_esa_s1_get_resorb reseof.list | sh
+  fi
+  #exit
+  di=`expr $di + 1`
+done #end-of-day-loop
diff --git a/sh/sh_ers2_link_raw b/sh/sh_ers2_link_raw
--- a/sh/sh_ers2_link_raw
+++ b/sh/sh_ers2_link_raw
@@ -37,8 +37,11 @@ while read line; do
     echo $line
     dfile="${EOLISA}/${line}.E2"
     if [ ! -s ${dfile} ]; then
-	echo "[]ERROR:data not found [${dfile}]!!"
-	exit 1
+      dfile="${EOLISA}/${line}.N1"
+      if [ ! -s ${dfile} ]; then
+      	echo "[]ERROR:data not found [${dfile}]!!"
+      	exit 1
+	    fi
     fi
     echo ln -s $dfile | sh
     if [ $? -eq 0 ]; then
diff --git a/sh/sh_esa_s1_intf_in_get_remain b/sh/sh_esa_s1_intf_in_get_remain
--- a/sh/sh_esa_s1_intf_in_get_remain
+++ b/sh/sh_esa_s1_intf_in_get_remain
@@ -30,6 +30,23 @@
 #   *Lines of data.in and scene.tab1 should correspond.
 
 prog=sh_esa_s1_intf_in_get_remain
+image_type=los_ll.png
+image_type=phasefilt_mask_ll.png
+image_type=_ll.png
+
+while [ "$1" != "" ]; do
+    case $1 in
+        -image_type)
+            image_type=$2
+            ;;
+        *)
+            echo "[]ERROR: invalid option $1"
+            exit 1
+            ;;
+       esac
+    shift 2
+done 
+
 
 if [ ! -s intf.in ]; then
     echo "[${prog}]ERROR:intf.in not exist!!"
@@ -57,9 +74,11 @@ if [ $ns -ne $nd ]; then
     exit 1
 fi
 
-days=`ls -lS intf_all_los_ll_png/*-los_ll.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
+#days=`ls -lS intf_all_los_ll_png/*-${image_type}.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
 #days=`ls -lS intf_all_los_ll_png/*-phasefilt_mask_ll.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
-
+days=`ls -lS intf_all_los_ll_png/*${image_type}* | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
+echo $days
+#exit
 
 rm -f intf.in.rem
 while read day; do
@@ -75,7 +94,7 @@ while read day; do
     ##n2=`grep -n $day2 data.in | awk -F: '{print $1}'`
     ##ymd2=`sed -n "${n2}p" scene.tab1 | awk '{print $1}'`
     
-    day1=`echo $day | awk -F: '{print $1}' | awk -F_ '{print substr($1,4)}'`
+    day1=`echo $day | awk -F: '{print $1}' | awk '{print substr($1,4,8)}'`
     year1=`echo $day1 | awk '{print substr($1,1,4)}'`
     mm1=`echo $day1 | awk '{print substr($1,5,2)}'`
     dd1=`echo $day1 | awk '{print substr($1,7,2)-1}'`
@@ -84,7 +103,7 @@ while read day; do
     #n1=`grep -n $day1 data.in | awk -F: '{print $1}'`
     #ymd1=`sed -n "${n1}p" scene.tab1 | awk '{print $1}'`
     #
-    day2=`echo $day | awk -F: '{print $2}' | awk -F_ '{print substr($1,4)}'`
+    day2=`echo $day | awk -F: '{print $2}' | awk '{print substr($1,4,8)}'`
     year2=`echo $day2 | awk '{print substr($1,1,4)}'`
     mm2=`echo $day2 | awk '{print substr($1,5,2)}'`
     dd2=`echo $day2 | awk '{print substr($1,7,2)-1}'`
@@ -93,8 +112,14 @@ while read day; do
     #n2=`grep -n $day2 data.in | awk -F: '{print $1}'`
     #ymd2=`sed -n "${n2}p" scene.tab1 | awk '{print $1}'`
     echo $ymd1 $ymd2 $n1 $n2 $day1 $day2
-    if [ -s ./intf_all_los_ll_png/${ymd1}_${ymd2}-los_ll.png ]; then
-	echo "[]WARNING:./intf_all_los_ll_png/${ymd1}_${ymd2}-los_ll.png exist! skip"
+    pwd
+    tmp=`find ./intf_all_los_ll_png/ -maxdepth 1 -name "${ymd1}_${ymd2}-*${image_type}*"`
+    #echo tmp is $tmp
+    #echo string is "${ymd1}_${ymd2}-*${image_type}*"
+    if [ "$tmp" != "" ]; then
+    ##if [ -s ./intf_all_los_ll_png/${ymd1}_${ymd2}-${image_type} ]; then
+	echo "[]WARNING:./intf_all_los_ll_png/${ymd1}_${ymd2}-${image_type} exist! skip"
+        #exit
 	continue
     else
 	echo $day >> intf.in.rem
diff --git a/sh/sh_esa_s1_intf_in_get_remain~ b/sh/sh_esa_s1_intf_in_get_remain~
--- a/sh/sh_esa_s1_intf_in_get_remain~
+++ b/sh/sh_esa_s1_intf_in_get_remain~
@@ -1,11 +1,14 @@
 #!/bin/sh
 
 # Name:
-#   sh_intf_in_rem
+#   sh_esa_s1_intf_in_get_remain
 #   
 
 # Purpose:
-#   
+#  Create input file (intf.in) for intf_tops.csh based upon the intf.in file,
+#    removing those already processed (with los_ll PNG files in 
+#    intf_all_los_ll_png/ directory copied by sh_sar_cp_los_ll_png script).
+
 
 # Example:
 #   
@@ -14,75 +17,101 @@
 #   
 
 # Algorigthm:
-#   
+#  For each line in intf.in file, if los_ll PNG file exists in 
+#  intf_all_los_ll_png/ directory, then skip it.
+#  
+#  Time in intf.in is YYYYMMDD, converted to YYYYDOY by checking YYYYMMMDD in 
+#  data.in and extract the time for the same line in scene.tab1.
 
 # Dependency:
-#   
+#   intf.in
+#   data.in
+#   scene.tab1 (copy of the original scene.tab)
+#   *Lines of data.in and scene.tab1 should correspond.
 
 prog=sh_esa_s1_intf_in_get_remain
+image_type=los_ll.png
+#image_type=phasefilt_mask_ll.png
+
+while [ "$1" != "" ]; do
+    case $1 in
+        -image_type)
+            image_type=$2
+            ;;
+        *)
+            echo "[]ERROR: invalid option $1"
+            exit 1
+            ;;
+       esac
+    shift 2
+done 
+
 
 if [ ! -s intf.in ]; then
     echo "[${prog}]ERROR:intf.in not exist!!"
     exit 1
 else
-    echo "#lines: `wc -l intf.in`"
+    echo "#lines: `wc -l intf.in | awk '{print $1}'`"
 fi
 
 if [ ! -s scene.tab1 ]; then
     echo "[${prog}]ERROR:scene.tab1 not exist!!"
     exit 1
 fi
-ns=`wc -l scene.tab1`
+ns=`wc -l scene.tab1 | awk '{print $1}'`
+echo "#lines of scene.tab1: $ns"
 
 if [ ! -s data.in ]; then
     echo "[${prog}]ERROR:data.in not exist!!"
     exit 1
 fi
-nd=`wc -l data.in`
+nd=`wc -l data.in | awk '{print $1}'`
+echo "#lines of data.in: $nd"
 
-if [ $nf -ne $nd ]; then
+if [ $ns -ne $nd ]; then
     echo "[${prog}]ERROR:the numbers of lines in scene.tab1 and data.in do not equal!!"
     exit 1
 fi
 
-days=`ls -lS intf_all_los_ll_png/*-los_ll.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
+#days=`ls -lS intf_all_los_ll_png/*-${image_type}.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
 #days=`ls -lS intf_all_los_ll_png/*-phasefilt_mask_ll.png | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
-
+days=`ls -lS intf_all_los_ll_png/*-${image_type}* | awk '{print $9}'|awk -F/ '{print $2}' | awk -F- '{print $1}'`
+echo $days
 
 rm -f intf.in.rem
 while read day; do
     echo $day
-    ##continue
-    #day1=`echo $day | awk -F: '{print $1}'`
-    day1=`echo $day | awk -F: '{print $1}' | awk -F_ '{print substr($1,4)}'`
-    n1=`grep -n $day1 data.in | awk -F: '{print $1}'`
-    ymd1=`sed -n "${n1}p" scene.tab1 | awk '{print $1}'`
-    #
-    #day2=`echo $day | awk -F: '{print $2}'`
-    day2=`echo $day | awk -F: '{print $2}' | awk -F_ '{print substr($1,4)}'`
-    n2=`grep -n $day2 data.in | awk -F: '{print $1}'`
-    ymd2=`sed -n "${n2}p" scene.tab1 | awk '{print $1}'`
-    
-    #day1=`echo $day | awk -F: '{print $1}' | awk -F_ '{print substr($1,4)}'`
-    #year1=`echo $day1 | awk '{print substr($1,1,4)}'`
-    #mm1=`echo $day1 | awk '{print substr($1,5,2)}'`
-    #dd1=`echo $day1 | awk '{print substr($1,7,2)-1}'`
-    #doyr1=`doy $year1 $mm1 $dd1 | head -1 | awk '{print $6}'`
-    #ymd1="${year1}${doyr1}"
+    ####continue
+    ###day1=`echo $day | awk -F: '{print $1}'`
+    ##day1=`echo $day | awk -F: '{print $1}' | awk -F_ '{print substr($1,4)}'`
     ##n1=`grep -n $day1 data.in | awk -F: '{print $1}'`
     ##ymd1=`sed -n "${n1}p" scene.tab1 | awk '{print $1}'`
-    ##
-    #day2=`echo $day | awk -F: '{print $2}' | awk -F_ '{print substr($1,4)}'`
-    #year2=`echo $day2 | awk '{print substr($1,1,4)}'`
-    #mm2=`echo $day2 | awk '{print substr($1,5,2)}'`
-    #dd2=`echo $day2 | awk '{print substr($1,7,2)-1}'`
-    #doyr2=`doy $year2 $mm2 $dd2 | head -1 | awk '{print $6}'`
-    #ymd2="${year2}${doyr2}"
+    ###
+    ###day2=`echo $day | awk -F: '{print $2}'`
+    ##day2=`echo $day | awk -F: '{print $2}' | awk -F_ '{print substr($1,4)}'`
     ##n2=`grep -n $day2 data.in | awk -F: '{print $1}'`
     ##ymd2=`sed -n "${n2}p" scene.tab1 | awk '{print $1}'`
-    echo $ymd1 $ymd2 $n1 $n2
-    if [ -s ./intf_all_los_ll_png/${ymd1}_${ymd2}-los_ll.png ]; then
-	echo "[]WARNING:./intf_all_los_ll_png/${ymd1}_${ymd2}-los_ll.png exist! skip"
+    
+    day1=`echo $day | awk -F: '{print $1}' | awk -F_ '{print substr($1,4)}'`
+    year1=`echo $day1 | awk '{print substr($1,1,4)}'`
+    mm1=`echo $day1 | awk '{print substr($1,5,2)}'`
+    dd1=`echo $day1 | awk '{print substr($1,7,2)-1}'`
+    doyr1=`doy $year1 $mm1 $dd1 | head -1 | awk '{printf("%03d", $6)}'`
+    ymd1="${year1}${doyr1}"
+    #n1=`grep -n $day1 data.in | awk -F: '{print $1}'`
+    #ymd1=`sed -n "${n1}p" scene.tab1 | awk '{print $1}'`
+    #
+    day2=`echo $day | awk -F: '{print $2}' | awk -F_ '{print substr($1,4)}'`
+    year2=`echo $day2 | awk '{print substr($1,1,4)}'`
+    mm2=`echo $day2 | awk '{print substr($1,5,2)}'`
+    dd2=`echo $day2 | awk '{print substr($1,7,2)-1}'`
+    doyr2=`doy $year2 $mm2 $dd2 | head -1 | awk '{printf("%03d",$6)}'`
+    ymd2="${year2}${doyr2}"
+    #n2=`grep -n $day2 data.in | awk -F: '{print $1}'`
+    #ymd2=`sed -n "${n2}p" scene.tab1 | awk '{print $1}'`
+    echo $ymd1 $ymd2 $n1 $n2 $day1 $day2
+    if [ -s ./intf_all_los_ll_png/${ymd1}_${ymd2}-${image_type} ]; then
+	echo "[]WARNING:./intf_all_los_ll_png/${ymd1}_${ymd2}-${image_type} exist! skip"
 	continue
     else
 	echo $day >> intf.in.rem
diff --git a/sh/sh_esa_s1_link_raworig b/sh/sh_esa_s1_link_raworig
--- a/sh/sh_esa_s1_link_raworig
+++ b/sh/sh_esa_s1_link_raworig
@@ -24,6 +24,8 @@ if [ "$esa_unzip" = "" ]; then
     exit 1
 fi
 
+echo esa_unzip $esa_unzip
+
 
 if [ "$1" = "" ]; then
     echo "Usage: sh_esa_link_raworig file [iw_type]"
@@ -48,7 +50,21 @@ while read line; do
 	echo "ERROR:data not found [${path_esa}/${dfile}]!!"
 	exit 1
     fi
-    echo find ${esa_unzip}/${dfile} -name "s1*-${iw_typ}-*-vv-*.tiff"
-    find ${esa_unzip}/${dfile}/ -name "s1*-${iw_typ}-*-vv-*.tiff" -exec ln -s {} \;
-    echo " ${dfile} linked."
+    file_tiff=`find ${esa_unzip}/${dfile} -name "s1*-${iw_typ}-*-vv-*.tiff"`
+    if [ "$file_tiff" == "" ]; then
+    	echo "[$PROG]ERROR: unzipped tiff file not found ($dfile)!!"
+    	exit 1
+    fi
+    
+    bname=`basename $file_tiff`
+    if [ -s $bname ]; then
+	#echo "[$PROG]INFO: already linked."
+	continue
+    fi
+
+    echo "[$PROG]INFO: linking $bname ..."
+    ln -s $file_tiff
+    #find ${esa_unzip}/${dfile}/ -name "s1*-${iw_typ}-*-vv-*.tiff" -exec ln -s {} \;
+    #echo " ${dfile} linked."
+    
 done < .tmp
diff --git a/sh/sh_esa_s1_link_raworig~ b/sh/sh_esa_s1_link_raworig~
--- a/sh/sh_esa_s1_link_raworig~
+++ b/sh/sh_esa_s1_link_raworig~
@@ -48,6 +48,13 @@ while read line; do
 	echo "ERROR:data not found [${path_esa}/${dfile}]!!"
 	exit 1
     fi
-    find ${esa_unzip}/${dfile} -name "s1*-${iw_typ}-*-vv-*.tiff" -exec ln -s {} \;
-    echo " ${dfile} linked."
+    file_tiff=`find ${esa_unzip}/${dfile} -name "s1*-${iw_typ}-*-vv-*.tiff"`
+    if [ "$file_tiff" == "" ]; then
+    	echo "[$PROG]ERROR: unzipped tiff file not found ($file_tiff)!!"
+    	exit 1
+   fi
+
+   echo "[$PROG]INFO: linking tiff file $file_tiff ..."
+    #find ${esa_unzip}/${dfile}/ -name "s1*-${iw_typ}-*-vv-*.tiff" -exec ln -s {} \;
+    #echo " ${dfile} linked."
 done < .tmp
diff --git a/sh/sh_esa_s1_unzip b/sh/sh_esa_s1_unzip
--- a/sh/sh_esa_s1_unzip
+++ b/sh/sh_esa_s1_unzip
@@ -19,6 +19,11 @@
 # Dependency:
 # 
 
+PROG=sh_esa_s1_unzip
+
+esa_data_node=/sar/esa.sentinel-1/alll
+#esa_data_node=/sar/esa.sentinel-1/links
+esa_data_node=/g4d/esa.data/s1
 
 if [ "$esa_unzip" = "" ]; then
     echo "ESA environment esa_unzip variable not set! Stopped!!"
@@ -26,54 +31,107 @@ if [ "$esa_unzip" = "" ]; then
 fi
 
 
-if [ "$esa_data" = "" ]; then
-    echo "ESA environment esa_data variable not set! Stopped!!"
-    exit 1
-fi
+#if [ "$esa_data" = "" ]; then
+#    echo "ESA environment esa_data variable not set! Stopped!!"
+#    exit 1
+#fi
 
 if [ "$1" == "" ]; then
-    echo "Usage: sh_esa_s1_unzip file [iw0|iw1|iw2|iw3]"
+    echo "[$PROG]Usage: $PROG file [iw0|iw1|iw2|iw3]"
     exit
 fi
-file=$1
 
-if [ "$2" = "" ]; then
+iws="iw1,iw2,iw3"
+
+is_check_done=n
+
+#two modes of input parameters
+if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
+
+  while [ "$1" != "" ]; do
+    case $1 in
+      -f|-file)
+        file=$2
+        ;;
+      -i|-iw)
+        iws=$2
+        ;;
+      -l|-local)
+        is_local=$2
+        ;;
+      -p|-path)
+        esa_data_node=$2
+        ;;
+      -update)
+        is_check_done=$2
+        ;;
+      *)
+        echo "[]ERROR: invalid option ($1)!!"
+        exit 1
+        ;;
+    esac
+    shift 2
+  done
+
+else  #mode 2
+
+  file=$1
+  if [ "$2" = "" ]; then
     echo "[INFO]iw_type not specified! Default iw1/iw2/iw3 will be extracted."
-    iw_typ=iw0
-else
-    iw_typ=$2
+    iws='iw1,iw2,iw3'
+  else 
+    iw_typs=`echo $2 | sed -e 's/,/ /g'`
+  fi
+  
+fi  #end-of-mode-2
+
+
+
+
+file_tmp=
+if [ "$is_check_done" == "y" ]; then
+
+  timestamp=`date | sed -e 's/ /_/g' | sed -e 's/:/-/g'`
+  file_tmp=_tmp_input_lst_${PROG}_${timestamp}
+  file2_tmp=_tmp_file_in_${PROG}_${timestamp}
+  grep '^ ' $file  > $file2_tmp
+  for iw in `echo $iws | sed -e 's/,/ /g'`; do
+    ii=`echo $iw | awk '{print substr($1,3,1)}'`
+    file_blt="F${ii}/baseline_table.dat"
+    if [ -s $file_blt ]; then
+      file_data="F${ii}/data.in"
+      break
+    fi
+  done
+  echo baseline file $file_blt
+
+  #\rm -rf $file_tmp
+  sid=`head -1 $file_data | awk -F- '{print substr($5,1,8)}'`
+  cat $file2_tmp | grep $sid > $file_tmp
+  while read line; do
+    sid=`echo $line | awk -F_ '{print substr($6,1,8)}'`
+    #echo sid $sid
+    tmp=`cat $file_blt | grep $sid`
+    if [ "$tmp" == "" ]; then
+      echo " $line" >> $file_tmp
+    fi
+  done < $file2_tmp
+  wc -l $file_tmp
+  file=$file_tmp
 fi
 
+echo file $file
 
-grep '^ ' $file | awk '{print $1}' > .tmp
-while read line; do
-    #echo $line
-    dfile="`echo $line | awk -F. '{print $1}'`.zip"
-    #echo ${path_esa}/${dfile}
-    if [ ! -s ${esa_data}/S1/${dfile} ]; then
-	echo "ERROR:data not found [${esa_data}/S1/${dfile}]!!"
-        continue
-	exit 1
-    fi
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1   -file $file -iw $iws
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1   -file $file -iw $iws | sh
 
-    ofile="`echo $line | awk -F. '{print $1}'`.SAFE"
-    #echo ${opath_esa}/${ofile}
-    if [ -d ${esa_unzip}/${ofile} ]; then
-	echo "INFO:already done [${esa_unzip}/${ofile}]. Skipped."
-	continue
-    fi
-    echo "unzip ${esa_data}/S1/${dfile}"
-    if [ "$iw_typ" = "iw1" ]; then
-	unzip ${esa_data}/S1/${dfile} -x *-vh-*  *iw2*  *iw3* -d ${esa_unzip}
-    elif [ "$iw_typ" = "iw2" ]; then
-	unzip ${esa_data}/S1/${dfile} -x *-vh-*  *iw1*  *iw3* -d ${esa_unzip}
-    elif [ "$iw_typ" = "iw3" ]; then
-	unzip ${esa_data}/S1/${dfile} -x *-vh-*  *iw1*  *iw2* -d ${esa_unzip}
-    elif [ "$iw_typ" = "iw0" ]; then
-	unzip ${esa_data}/S1/${dfile} -x *-vh-*  -d ${esa_unzip}
-    else
-	echo "[]WARNING:wrong sub-swatch option $iw_typ !! Skipped!"
-    fi
-    #exit
-done < .tmp
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1.2 -file $file -iw $iws
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1.2 -file $file -iw $iws | sh
 
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1.3 -file $file -iw $iws
+echo sh_esa_s1_unzip_node -path /g4d/esa.data/s1.3 -file $file -iw $iws | sh
+
+
+if [ "$file_tmp" != "" ]; then
+  \rm -f $file_tmp $file2_tmp
+fi
diff --git a/sh/sh_new b/sh/sh_new
--- a/sh/sh_new
+++ b/sh/sh_new
@@ -43,7 +43,36 @@ echo "#   $ofile" >> $ofile
 linu=`expr $linu + 1`
 sed -n "${linu},$ p" $mfile >> $ofile
 
+echo "PROG=$ofile" >> $ofile
+
+echo "">> $ofile
+echo 'timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`' >> $ofile
+
+
 # add executable property
 chmod +x $ofile
 
+
+cat <<eob >> $ofile
+
+path_old=\`pwd\`
+
+usage(){
+  echo "[\$PROG]Usage: \${PROG} "
+  echo "[\$PROG]Usage: e.g.,"
+  echo "[\$PROG]Usage: \${PROG} "
+}
+
+while [ "\$1" != "" ]; do
+  case \$1 in
+    *)
+      echo "[\$PROG]ERROR: invalid option (\$1)!!"
+      usage
+      exit 1
+      ;;
+  esac
+  shift 2  
+done
+
+eob
 # the END
diff --git a/sh/sh_run_gamit b/sh/sh_run_gamit
--- a/sh/sh_run_gamit
+++ b/sh/sh_run_gamit
@@ -99,6 +99,8 @@ hfile_path=/home/tianyf/hfiles
 #script_file to be deleted
 script_file=non #default not delete the running script, except batched by SLURM.
 
+ftp_root_prefix=pub
+#ftp_root_preifx=gnss
 
 # process command-line parameters
 #####################################################
@@ -196,7 +198,9 @@ is_reg_lgn=`echo $regs | awk '{print index($0,"REG_LGN")}'`
 
 #hard-wired parameter
 #host="210.31.68.163"
-host="ftp://${host}"
+#host="ftp://${host}"
+host="http://${host}"
+
 
 #begin re-run
 echo " >re-run ..."
@@ -243,46 +247,54 @@ while [ $i -lt $ndays ]; do
 	#${ftp_prog} ${host}/pub/rinex/${year}/${doy}/${yr}d/${site}${doy}0.${yr}d.Z
 	#${ftp_prog} ${host}/pub1/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z
 	#${ftp_prog} ${host}/pub1/rinex/${year}/${doy}/${yr}d/${site}${doy}0.${yr}d.Z
-	#wget -nc ${host}/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z >> $logfile 2>>${logfile}
+	wget -nc ${host}/${ftp_root_prefix}/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z >> $logfile 2>>${logfile}
+        wget -nc ${host}/${ftp_root_prefix}/rinex/${year}/${doy}/${site}${doy}0.${yr}d.gz >> $logfile 2>>${logfile}
+        #\cp /g10a/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}[od].Z .
+        #\cp /g10a/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}[od].gz .
+
 	#wget -nc ${host}/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}o.Z >> $logfile 2>>${logfile}
 	
  #for FTP server as GPSDC
-        \cp -f /dcd0/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
-        \cp -f /dcd0/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}o.Z . >> $logfile 2>>${logfile}
+        #\cp -f /dcd0/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
+        #\cp -f /dcd0/ftp/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}o.Z . >> $logfile 2>>${logfile}
 
         #for FTP server as VMICD
-        \cp -f /home/FTP/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
-        \cp -f /home/FTP/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}o.Z . >> $logfile 2>>${logfile}
+        #\cp -f /home/FTP/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
+        #\cp -f /home/FTP/pub/rinex/${year}/${doy}/${site}${doy}0.${yr}o.Z . >> $logfile 2>>${logfile}
 
 	#\cp -f /igs/pub/rinex/${year}/${doy}/${site}${doy}?.${yr}?.Z .  >> $logfile 2>>${logfile}
+        if [ -d /sar/${ftp_root_prefix}/rinex/${year}/${doy} ]; then
+          \cp -f /sar/${ftp_root_prefix}/rinex/${year}/${doy}/${site}${doy}?.${yr}?.*[zZ] .  >> $logfile 2>>${logfile}
+        fi
+
 	#for CMONOC network
 	if [ $is_reg_lutai_cgps -gt 0 ]; then
-	    \cp -f /home/lutai/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
+	    \cp -f /home/lutai/rinex/${year}/${doy}/${site}${doy}0.${yr}d.*[zZ] . >> $logfile 2>>${logfile}
 	fi
 	if [ $is_reg_lutai_sgps -gt 0 ]; then
-	    \cp -f /home/lutai/survey.mode/reg${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile 2>>${logfile}
+	    \cp -f /home/lutai/survey.mode/reg${year}/${doy}/${site}${doy}0.${yr}d.*[zZ] . >> $logfile 2>>${logfile}
 	fi
 	if [ $is_reg_cmonoc_cont -gt 0 ]; then
-	    \cp -f /home/cmonoc/DATA/${year}/${doy}/${site}${doy}0.${yr}d.Z .  >> $logfile  2>>${logfile}
+	    \cp -f /home/cmonoc/DATA/${year}/${doy}/${site}${doy}0.${yr}d.*[zZ] .  >> $logfile  2>>${logfile}
 	   #\cp -f /home/cmonoc/DATA/${year}/${doy}/${site}${doy}0.${yr}d.Z .  >> $logfile 2>>${logfile}
 	fi
 	if [ $is_reg_cmonoc_survey_mode -gt 0 ]; then
-	    \cp -f /home/cmonoc/survey.mode/${year}/${doy}/${site}${doy}?.${yr}d.Z . >> $logfile  2>>${logfile}
+	    \cp -f /home/cmonoc/survey.mode/${year}/${doy}/${site}${doy}?.${yr}d.*[zZ] . >> $logfile  2>>${logfile}
 	fi
 	#For TigiCAS network
 	if [ $is_reg_tigicas -gt 0 ]; then
-	    \cp -f /home/TigiCAS/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z . >> $logfile  2>>${logfile}
+	    \cp -f /home/TigiCAS/rinex/${year}/${doy}/${site}${doy}0.${yr}d.*[zZ] . >> $logfile  2>>${logfile}
 	fi
 	#for local yushu quake
 	#\cp -f /export/home/tianyf/gpse/rerun.yushu/data/rinex/${year}/${doy}/${site}${doy}0.${yr}o . >> $logfile  2>>${logfile}
 	#for Geonet
 	if [ $is_reg_nepal -gt 0 ]; then
-	    #\cp -f /export/home/nepal/rinex/${year}/${doy}/${site}${doy}0.${yr}d.Z .  >> $logfile  2>>${logfile}
+	    #\cp -f /export/home/nepal/rinex/${year}/${doy}/${site}${doy}0.${yr}d.*[zZ] .  >> $logfile  2>>${logfile}
 	    \cp -f /home/nepal/rinex/${year}/${doy}/${site}${doy}?.${yr}?.gz . >> $logfile  2>>${logfile}
 	    \cp -f /home/nepal/rinex/${year}/${doy}/${site}${doy}?.${yr}?.Z .  >> $logfile  2>>${logfile}
 	fi
 	if [ $is_reg_wenchuan -gt 0 ]; then
-	    \cp -f /home/wenchuan/rinex/${year}/${doy}/${site}${doy}?.${yr}d.Z . >> $logfile  2>>${logfile}
+	    \cp -f /home/wenchuan/rinex/${year}/${doy}/${site}${doy}?.${yr}d.*[zZ] . >> $logfile  2>>${logfile}
 	fi
 	if [ $is_reg_beijing -gt 0 ]; then
 	    files=`find  /home/beijing/raw/${year}/${doy}/ -iname "*${site}*.*o*"`
@@ -308,7 +320,9 @@ while [ $i -lt $ndays ]; do
 
 	#lhasa campaign
 	if [ $is_reg_lgn -gt 0 ]; then
-	    \cp -f /home/lhasa_block/${year}/${doy}/${site}${doy}0.${yr}o* .  >> $logfile 2>>${logfile}
+	    #\cp -f /g10a/ftp/pub/lhasa_block/daily/${year}/${doy}/${site}${doy}0.${yr}o* .  >> $logfile 2>>${logfile}
+            \cp -f /g16n/lgn/${year}/${doy}/${site}${doy}0.${yr}o* .  >> $logfile 2>>${logfile}
+
         #\cp -f /home/eBACKUP/LasaData/rinex/${year}/${doy}/${site}${doy}0.${yr}o* .  >> $logfile 2>>${logfile}
 	fi
 
@@ -330,8 +344,9 @@ while [ $i -lt $ndays ]; do
     echo " >>uncompress rinex files"
     sh_crx2rnx  -f ???????0.??d.Z >> $logfile 2>>${logfile}
     #uncompress *.??o.Z files
-    \uncompress -f *.??o.Z
-    \gunzip -f *.??o.gz
+    \uncompress -f *.??[do].Z
+    \gunzip -f *.??[do].gz
+    sh_crx2rnx -f *d
 
     #exit
     echo " >>get met.."
@@ -353,7 +368,7 @@ while [ $i -lt $ndays ]; do
     mkdir -p ${rerun_root}/brdc
     cd ${rerun_root}/brdc
     #\ln -s -f ${igs_root}/nav/${year}/${doy}/brdc${doy}0.${yr}n.Z .
-    ${ftp_prog} ${host}/pub/nav/${year}/${doy}/brdc${doy}0.${yr}n.Z  >> $logfile 2>>${logfile}
+    ${ftp_prog} ${host}/${ftp_root_prefix}/nav/${year}/${doy}/brdc${doy}0.${yr}n.Z  >> $logfile 2>>${logfile}
     #delete file with zero size?
     #if [ ! -s brdc${doy}0.${yr}n.Z ]; then
 	#\rm -f brdc${doy}0.${yr}n.Z
@@ -368,14 +383,68 @@ while [ $i -lt $ndays ]; do
 	continue
     fi
     #exit
-    \uncompress -f brdc${doy}0.${yr}n.Z
-    if [ $? -ne 0 ]; then
+   
+    ls -l
+    #is_Z=`cat brdc${doy}0.${yr}n.Z | uncompress | grep 'not in compressed format'`
+    cat brdc${doy}0.${yr}n.Z | uncompress 
+    if [ $? -eq 0 ]; then
+    #if [ "$is_Z" == "" ]; then
+      \uncompress -f brdc${doy}0.${yr}n.Z
+    else
+      \gunzip -f brdc${doy}0.${yr}n.Z
+    fi
+    
+    #if [ $? -ne 0 ]; then
+    if [ ! -s brdc${doy}0.${yr}n ]; then
+        ls -l #brdc${doy}0.${yr}n
 	echo "Error:  unable to unzip bbrdc/nav file! Skipping"  >> $logfile 2>>${logfile}
 	i=`expr $i + 1`
 	doy=`expr $doy + 1`
 	continue
     fi
     \rm -f brdc${doy}0.${yr}n.Z
+
+
+#link ionex
+    echo " >>get ionex.."
+    case $orbit in
+      IGSF)
+        orb_typ=igs
+        ;;
+      IGSR)
+        orb_typ=igr
+        ;;
+      *)
+        echo "[]ERROR: wrong type orbit ($orbit)!!"
+        exit 1
+        ;;
+    esac
+    mkdir -p ${rerun_root}/ionex
+    cd ${rerun_root}/ionex
+    #\ln -s -f ${igs_root}/nav/${year}/${doy}/brdc${doy}0.${yr}n.Z .
+    ${ftp_prog} ${host}/${ftp_root_prefix}/ionex/${year}/${doy}/${orb_typ}g${doy}0.${yr}i.Z  >> $logfile 2>>${logfile}
+    #delete file with zero size?
+    #if [ ! -s igsg${doy}0.${yr}i.Z ]; then
+	    #\rm -f brdc${doy}0.${yr}n.Z
+    #fi
+    #echo "zero?"
+    if [ ! -s ${orb_typ}g${doy}0.${yr}i.Z ]; then
+    	echo "WARNING: No ionex file exist! Skipping"  >> $logfile 2>>${logfile}
+    	\rm -f ${orb_typ}g${doy}0.${yr}i.Z
+    	##i=`expr $i + 1`
+    	##doy=`expr $doy + 1`
+    	###exit
+    	##continue
+    fi
+    #exit
+    \uncompress -f ${orb_typ}g${doy}0.${yr}i.Z
+    if [ $? -ne 0 ]; then
+    	echo "Error:  unable to unzip ionex file! Skipping"  >> $logfile 2>>${logfile}
+    	##i=`expr $i + 1`
+    	##doy=`expr $doy + 1`
+    	##continue
+    fi
+    #exit
 
 
 #link orbit files
@@ -390,7 +459,7 @@ while [ $i -lt $ndays ]; do
 	${ftp_prog} ${host}/pub/gfiles/${gpsw}/gpgga${y}.${doy}.Z  >> $logfile 2>>${logfile}
 	\uncompress -f ${igs_root}/gfiles/${gpsw}/gpgga${y}.${doy}.Z .  >> $logfile 2>>${logfile}
 	\rm -f gpgga${y}.${doy}.Z
-    elif [ "${orbit}" = "IGSF" ]; then
+    elif [ "${orbit}" = "IGSF"  -o "${orbit}" = "IGFF" ]; then
 	if [ -f ${rerun_root}/gfiles/gigsf${y}.${doy} ]; then
 	    #yearGfile=`head -1 ${rerun_root}/gfiles/gigsf${y}.${doy} | awk '{print $1}'`
 	    #if [ $yearGfile -eq $year} ]; then
@@ -400,15 +469,22 @@ while [ $i -lt $ndays ]; do
 	    mkdir ${rerun_root}/igs
 	    cd ${rerun_root}/igs
 	    #\ln -s -f ${igs_root}/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z .
-	    ${ftp_prog} ${host}/pub/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z >> $logfile 2>>${logfile}
-	    \uncompress -f igs${gpsw}${gpsd}.sp3.Z  >> $logfile 2>>${logfile}
+	    ${ftp_prog} ${host}/${ftp_root_prefix}/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z >> $logfile 2>>${logfile}
+            cat igs${gpsw}${gpsd}.sp3.Z | uncompress
+            if [ $? -eq 0 ]; then
+  	      \uncompress -f igs${gpsw}${gpsd}.sp3.Z  >> $logfile 2>>${logfile}
+            else
+              gunzip  -f igs${gpsw}${gpsd}.sp3.Z 
+            fi
 	    links.arc J2000 ${year} usno >> $logfile 2>>${logfile}
 	    sh_sp3fit -f igs${gpsw}${gpsd}.sp3 -o igsf -t -u -m 0.200 >> $logfile 2>>${logfile}
+	    ##sh_sp3fit -f igs${gpsw}${gpsd}.sp3 -o igff -t -u -m 0.200 >> $logfile 2>>${logfile}
 	    \cp -f gigsf${y}.${doy} ../gfiles >> $logfile 2>>${logfile}
+	    \cp -f gigfg${y}.${doy} ../gfiles >> $logfile 2>>${logfile}
 	    #echo "not supported, yet!"
 	    #exit 1
 	fi
-    elif [ "${orbit}" = "IGSR" ]; then
+    elif [ "${orbit}" = "IGSR" -o "${orbit}" = "IGRR" ]; then
 	if [ -f ${rerun_root}/gfiles/gigsr${y}.${doy} ]; then
 	    echo "G-file exist: ${rerun_root}/gfiles/gigsf${y}.${doy}  skipping..." >> $logfile
 	else
@@ -416,12 +492,22 @@ while [ $i -lt $ndays ]; do
 	    cd ${rerun_root}/igs
 	    #\ln -s -f ${igs_root}/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z .
 
-	    ${ftp_prog} ${host}/pub/products/${gpsw}/igr${gpsw}${gpsd}.sp3.Z >> $logfile 2>>${logfile}
-	    \uncompress -f igr${gpsw}${gpsd}.sp3.Z
+	    ${ftp_prog} ${host}/${ftp_root_prefix}/products/${gpsw}/igr${gpsw}${gpsd}.sp3.Z >> $logfile 2>>${logfile}
+            cat igr${gpsw}${gpsd}.sp3.Z | uncompress
+            if [ $? -eq 0 ]; then
+         	    \uncompress -f igr${gpsw}${gpsd}.sp3.Z
+            else
+              gunzip -f igr${gpsw}${gpsd}.sp3.Z
+            fi
+            #exit
 	    links.arc J2000 ${year} usno
             echo "sh_sp3fit -f igr${gpsw}${gpsd}.sp3 -o igsr -t -u -m 0.200" >> $logfile
 	    sh_sp3fit -f igr${gpsw}${gpsd}.sp3 -o igsr -t -u -m 0.200 >> $logfile 2>>${logfile}
-	    \cp -f gigsr${y}.${doy} ../gfiles
+	    ##sh_sp3fit -f igr${gpsw}${gpsd}.sp3 -o igrr -t -u -m 0.200 >> $logfile 2>>${logfile}
+	    \cp -f gigsr${y}.${doy} ../gfiles >> $logfile 2>>${logfile}
+            \cp -f gigsg${y}.${doy} ../gfiles >> $logfile 2>>${logfile}
+            \cp -f gigrg${y}.${doy} ../gfiles >> $logfile 2>>${logfile}
+
 	    #echo "not supported, yet!"
 	    #exit 1
 	fi
@@ -432,8 +518,9 @@ while [ $i -lt $ndays ]; do
 	    mkdir ${rerun_root}/igs
 	    cd ${rerun_root}/igs
 	    #\ln -s -f ${igs_root}/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z .
-	    ${ftp_prog} ${host}/pub/products/${gpsw}/igu${gpsw}${gpsd}_18.sp3.Z
+	    ${ftp_prog} ${host}/${ftp_root_prefix}/products/${gpsw}/igu${gpsw}${gpsd}_18.sp3.Z
 	    \uncompress -f igu${gpsw}${gpsd}*.sp3.Z
+            gunzip  -f igu${gpsw}${gpsd}*.sp3.Z
 	    links.arc J2000 ${year} usno
 	    sh_sp3fit -f igu${gpsw}${gpsd}_18.sp3 -o igsu -t -d ${year} ${doy} -u -m 0.200
 	    \cp -f gigsu${y}.${doy} ../gfiles
@@ -447,7 +534,7 @@ while [ $i -lt $ndays ]; do
 	    mkdir ${rerun_root}/igs
 	    cd ${rerun_root}/igs
 	    #\ln -s -f ${igs_root}/products/${gpsw}/igs${gpsw}${gpsd}.sp3.Z .
-	    ${ftp_prog} ${host}/pub/products/${gpsw}/repro1/ig1${gpsw}${gpsd}.sp3.Z
+	    ${ftp_prog} ${host}/${ftp_root_prefix}/products/${gpsw}/repro1/ig1${gpsw}${gpsd}.sp3.Z
 	    \uncompress -f ig1${gpsw}${gpsd}*.sp3.Z
 	    links.arc J2000 ${year} usno
 	    sh_sp3fit -f ig1${gpsw}${gpsd}.sp3 -o igsf -t -d ${year} ${doy} -u -m 0.200
@@ -477,6 +564,7 @@ while [ $i -lt $ndays ]; do
 
     echo " running sh_gamit ..."
     echo "sh_gamit -expt ${expt} -d ${year} ${doy} -orbit ${orbit} -met -noftp -yrext  -dopt a b c D H d k x y p t"
+    #exit 1
 #run sh_gamit
     cd ${rerun_root}
     sh_gamit -expt ${expt} -d ${year} ${doy} -orbit ${orbit} -met -noftp -yrext  -dopt a b c D H d k x y p t  >> $logfile 2>>${logfile}
diff --git a/sh/sh_sar_cal_sat_incidence b/sh/sh_sar_cal_sat_incidence
--- a/sh/sh_sar_cal_sat_incidence
+++ b/sh/sh_sar_cal_sat_incidence
@@ -19,6 +19,10 @@
 # Dependency:
 #   
 
+PROG=sh_sar_cal_sat_incidence
+
+
+
 SAT=SAT
 file=vel_ll
 
@@ -31,7 +35,7 @@ while [ "$1" != "" ]; do
 	    file=$2
 	    ;;
 	*)
-	    echo "[]ERROR: invalid options $1 !!"
+	    echo "[$PROG]ERROR: invalid options $1 !!"
 	    exit
 	    ;;
     esac
@@ -39,16 +43,23 @@ while [ "$1" != "" ]; do
 done
 echo Satellite sensor: ${SAT}
 
+
+if [ ! -s ../topo/dem.grd ]; then
+	echo "[$PROG]ERROR: dem.grd is missing (`pwd`/../topo/dem.grd)!!"
+	exit 1
+fi 
+
+
 if [ ! -s ${file}.xyz ]; then
     echo "0. first convert ${file}.grd to XYZ format"
     if [ ! -s ${file}.grd ]; then
-	echo "[]ERROR: ${file}.grd is missing!!"
+	echo "[$PROG]ERROR: ${file}.grd is missing!!"
 	exit 1
     fi
-    grd2xyz ${file}.grd | grep -v NaN | awk '{print "",$0}' > ${file}.xyz
+    gmt grd2xyz ${file}.grd | grep -v NaN | awk '{print "",$0}' > ${file}.xyz
 fi
 
-cat ${file}.xyz | awk '{print $1,$2}' > tmp_cal_sat_indicence.llde
+cat ${file}.xyz | awk '{print $1,$2}' > _tmp_cal_sat_indicence.llde
 
 files_prm=`ls ../topo/*.PRM | sort`
 if [ $? -ne 0 ]; then
@@ -58,29 +69,32 @@ fi
 file_prm=`echo $files_prm | head -1 | awk '{print $1}'`
 sid=`basename $file_prm | awk -F- '{print $3}'`
 
-#files_led=`ls ../SLC/LED*${sid}*`
-#files_led=`find ../SLC -maxdepth 1 -name "LED*${sid}*"`
-file_led="../raw/`grep led_file $file_prm | awk '{print $3}'`"
-if [ ! -s ${file_led} ]; then
-    echo "[]ERROR:no LED file found!!"
+
+led_name=`grep led_file $file_prm | awk '{print $3}'`
+if [ ! -s $led_name ]; then
+  #for single subswath processing (F1/F2/F3)
+  if [ -s ../raw/$led_name ]; then
+    \cp -f ../raw/$led_name .
+  elif [ -s ../topo/$led_name ]; then
+    \cp -f ../topo/$led_name .
+  elif [ -s ../../F1/raw/$led_name ]; then
+    \cp -f ../../F1/raw/$led_name .
+  else
+    echo "[]ERROR:no LED file found($lef_name)!!"
     exit 1
+  fi
+
 fi
-#file_led=`echo $files_led | head -1 | awk '{print $1}'`
-echo ln -s $file_led
-echo ln -s $file_led | sh
 
 echo ln -s $file_prm 
 echo ln -s $file_prm | sh 
 file_prm=`basename $file_prm`
 
-echo ln -s ../topo/dem.grd
-echo ln -s ../topo/dem.grd | sh 
-
-echo add_look.csh tmp_cal_sat_indicence.llde $file_prm $SAT dem.grd
-echo add_look.csh tmp_cal_sat_indicence.llde $file_prm $SAT dem.grd | sh
+echo add_look.csh _tmp_cal_sat_indicence.llde $file_prm $SAT ../topo/dem.grd
+echo add_look.csh _tmp_cal_sat_indicence.llde $file_prm $SAT ../topo/dem.grd | sh
 #exit
 
-cat tmp_cal_sat_indicence.lltnde | awk '{print $4,$5,$6}' | sar_cal_sat_incidence | awk '{print 90-$1}' > tmp_incidences
-cat tmp_incidences | mean | awk '{print $1}'
+cat _tmp_cal_sat_indicence.lltnde | awk '{print $4,$5,$6}' | sar_cal_sat_incidence | awk '{print 90-$1}' > _tmp_incidences
+cat _tmp_incidences | mean | awk '{print $1}'
 
-\rm -f ./dem.grd
+
