update 20230504

diff --git a/sh/sh_asf_s1_get_slc_py b/sh/sh_asf_s1_get_slc_py
--- a/sh/sh_asf_s1_get_slc_py
+++ b/sh/sh_asf_s1_get_slc_py
@@ -13,7 +13,7 @@
 # Modifications:
 #   
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
@@ -26,15 +26,27 @@ timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
 path_old=`pwd`
 
 usage_of_it(){
-  echo "[$PROG]HELP: ${PROG} "
-  echo "[$PROG]HELP:   [-f|-file PY_FILE]"
-  echo "[$PROG]HELP:   [-ac|-aria2_conf ARIA2_CONF_FILE]"
-  echo "[$PROG]HELP:   [-u|-user EARTHDATA_USER_NAME (only for DIPP)]"
-  echo "[$PROG]HELP:   [-o|-opath OUTPUT_PATH]"
 
-  echo "[$PROG]HELP:   [-h|-help]"
-  echo "[$PROG]HELP: e.g.,"
-  echo "[$PROG]HELP:   ${PROG} "
+cat <<eob
+$PROG
+|_Use aria2 to download S1 SLC zip files in ASF Python downloader (download*.py).
+  https://search.asf.alaska.edu/  (search and download Python script)
+|<
+  -f|-file PY_FILE
+  -ac|-aria2_conf ARIA2_CONF_FILE
+  [-p|-path OUTPUT_PATH]
+    default: \`pwd\`
+  [-h|-help]
+|e.g.,
+  $PROG -file download-all-2021-01-07_06-49-41.py
+    -ac /home/tianyf/earthdata_yftian.txt
+    -path /sar/s1/
+  Sample aria2 account file:
+    http-user=your_account
+    http-passwd=your_password
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+
 }
 
 
@@ -48,7 +60,7 @@ file_aria2_conf=
 
 file_py=
 
-opath=`pwd`
+path=`pwd`
 
 
 if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
@@ -63,8 +75,8 @@ if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
       -u|-user)
         user=$2
         ;;
-      -o|-opath)
-        opath=$2
+      -p|-path)
+        path=$2
         ;;
       -w1)
         w1=$2
@@ -77,7 +89,7 @@ if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
         exit 1
         ;;
       *)
-        echo "[$PROG]ERROR: invalid option ($1)!!"
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
         usage_of_it
         exit 1
         ;;
@@ -88,7 +100,7 @@ else
   file_py=$1
   
   if [ "$2" != "" ]; then
-    opath=$2
+    path=$2
   fi
   
   if [ "$3" != "" ]; then
@@ -100,18 +112,35 @@ if [ "$file_aria2_conf" == "" -o "$file_aria2_conf" == "null" ]; then
   file_aria2_conf=${HOME}/iGPS.addon/sh/aria2.conf.${user}
 fi
 
+
+if [ "$file_aria2_conf" == "" ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no ASF login information file given!!"
+  exit 1
+fi
+
+if [ "$file_py" == "" ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no ASF Python Downloader file given!!"
+  exit 1
+fi
+
 ext=${file_py##*.}
 echo $file_py $ext
 if [ "$ext" != "py" ]; then
-  echo "[$PROG]ERROR: wrong input file type (${file_py})!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: wrong input file type (${file_py})!!"
   exit 1
 fi
 #exit
+
+if [ ! -s $file_py ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: ASF Python Downloader file not exist ($file_py)!!"
+  exit 1
+fi
+
 files=`cat $file_py | sed -e 's/https/https\n/g' | grep '.zip' | grep S1 | grep _IW_SLC__ | awk -F\" '{print $1}' | awk -F\/ '{print $6}' |sort `
 echo $files
 #exit
 
-cd $opath
+cd $path
 pwd
 
 
@@ -160,4 +189,4 @@ for file in $files; do
   #exit
 done
 
-
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_asf_s1_get_slc_roi b/sh/sh_asf_s1_get_slc_roi
--- a/sh/sh_asf_s1_get_slc_roi
+++ b/sh/sh_asf_s1_get_slc_roi
@@ -13,7 +13,7 @@
 # Modifications:
 #   
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
@@ -35,17 +35,27 @@ timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
 path_old=`pwd`
 
 usage_of_it(){
-  echo "[$PROG]HELP: ${PROG} "
-  echo "[$PROG]HELP:   [-ac|-aria2_conf ARIA2_CONF_FILE]"
-  echo "[$PROG]HELP:   [-u|-user EARTHDATA_USER_NAME (only for DIPP)]"
-  echo "[$PROG]HELP:   [-p|-path OUTPUT_PATH]"
-  echo "[$PROG]HELP:   [-r|-roi ROI_FILE]"
-  echo "[$PROG]HELP:   [-w1 WEEKS_AGO_TIME_START]"
-  echo "[$PROG]HELP:   [-w2 WEEKS_AGO_TIME_END]"
-
-  echo "[$PROG]HELP:   [-h|-help]"
-  echo "[$PROG]HELP: e.g.,"
-  echo "[$PROG]HELP:   ${PROG} "
+cat <<eob
+${PROG}
+|_Use aria2 to download S1 SLC zip files returned by ASF API search.
+  https://docs.asf.alaska.edu/api/basics/
+|+
+  -sh_asf_s1_query
+  -aria2
+|<
+  -r|-roi ROI_FILE_KML
+  -ac|-aria2_conf ARIA2_CONF_FILE
+  [-p|-path OUTPUT_PATH]
+    default: \`pwd\`
+  [-w1 FROM_w1_WEEKS_AGO]
+    default: 3
+  [-w2 TO_w2_WEEKS_AGO]
+    default: 0
+  [-h|-help|--help]
+|e.g.,
+  ${PROG} 
+(c)iGPS (https://github.com/igps-ftk/)
+eob
 }
 
 if [ "$1" == "" ]; then
@@ -58,13 +68,18 @@ this_host=`hostname`
 w1=3 #download data backward three weeks
 w2=0
 
-roi_file=   #region of interest in KML polygon format
+file_roi=   #region of interest in KML polygon format
 user=   #EARTHDATA username (only for DIPP system; please specify your own aria2.conf file with -ac option)
 file_aria2_conf=null
 
-orb_types='ASCENDING DESCENDING'
-path=
+orb_type='ASCENDING'
+orb_type=DESCENDING
+orb_type=
 
+path=`pwd`
+
+file_tmp_py=_tmp_${PROG}_${timestamp}_download.py
+#echo $file_tmp_py
 
 while [ "$1" != "" ]; do
   case $1 in
@@ -78,7 +93,7 @@ while [ "$1" != "" ]; do
       path=$2
       ;;
     -r|-roi)
-      roi_file=$2
+      file_roi=$2
       ;;
     -w1)
       w1=$2
@@ -91,8 +106,8 @@ while [ "$1" != "" ]; do
       exit 1
       ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
       usage_of_it
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
       exit 1
       ;;
   esac
@@ -100,80 +115,83 @@ while [ "$1" != "" ]; do
 done
 
 
+
 #hardwired parameters for DIPP system only
 ###>>>DIPP
-if [ "$roi_file" == "" ]; then #DIPP defaults
+if [ "$file_roi" == "" ]; then #DIPP defaults
   #check the data root directory
   if [ "$esa_data" == "" ]; then
-    ehco "[$PROG]ERROR: environment variable esa_data not set!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: environment variable esa_data not set!!"
     exit 1
   fi
   if [ ! -d $esa_data ]; then
-    ehco "[$PROG]ERROR: esa_data ($esa_data) not exist!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: esa_data ($esa_data) not exist!!"
     exit 1
   fi
   
-  roi_file=${esa_data}/vector/L_.roi_china_east.kml
-  roi_file=${esa_data}/vector/roi_china_20210216.kml
-  roi_file=${esa_data}/vector/L0.roi_tibet_20210327.kml
-  roi_file=${esa_data}/vector/L0.roi_tibet_20220325.kml
-  #roi_file=${esa_data}/vector/L0.roi_tibet.kml
-  #roi_file=${esa_data}/vector/L0.roi_tibet.arv.kml
-  #roi_file=${esa_data}/vector/L0.roi_tibet_20210327_chuandian.psxy
+  file_roi=${esa_data}/vector/L_.roi_china_east.kml
+  file_roi=${esa_data}/vector/roi_china_20210216.kml
+  file_roi=${esa_data}/vector/L0.roi_tibet_20210327.kml
+  file_roi=${esa_data}/vector/L0.roi_tibet_20220325.kml
+  #file_roi=${esa_data}/vector/L0.roi_tibet.kml
+  #file_roi=${esa_data}/vector/L0.roi_tibet.arv.kml
+  #file_roi=${esa_data}/vector/L0.roi_tibet_20210327_chuandian.psxy
   
   case $this_host in
     gpsac15)
-      #orb_types='ASCENDIGN'
+      #orb_type='ASCENDIGN'
       path=/g15a/gsar/china_east/S1.3
       ;;
-    gpsac12)
-      orb_types='ASCENDING'
+    gpsac12|gpsac-4)
+      orb_type='ASCENDING'
       path=/g14i/esa.data/china_east/S1.3
       path=/g18h/gsar/tmp
       path=/g19b/gsar/tmp/
       path=/g8g/gsar/tmp/
       ;;
     gpsac17)
-      #orb_types='DESCENDING'
-      roi_file=${esa_data}/vector/L0.roi_tibet.arv.kml
+      #orb_type='DESCENDING'
+      file_roi=${esa_data}/vector/L0.roi_tibet.arv.kml
       path=/g17c/gsar/asf_tibet/S1
       #path=/g17b/gsar/asf_tibet/S1/
       ;;
     SNOW1)
-      #orb_types='DESCENDING'
+      #orb_type='DESCENDING'
       path=/cygdrive/d/esa.data/asf_tibet/S1
       ;;
-    gpsac16|gpsac4)
-      orb_types='DESCENDING'
+    gpsac16)
+      orb_type='DESCENDING'
       path=/g18h/gsar/tmp2/
       path=/g19b/gsar/tmp2/
       path=/g8g/gsar/tmp2/
       ;; 
     gpsac18)
-      #orb_types='DESCENDING'
+      #orb_type='DESCENDING'
       path=/g18h/gsar/tmp/
       ;;
     node4)
-      orb_types='DESCENDING'
+      orb_type='DESCENDING'
       path=/sar/esa.sentinel-1/in-progress/d000/
-      roi_file=${esa_data}/vector/roi_northeast.kml
+      file_roi=${esa_data}/vector/roi_northeast.kml
       ;;
     node5)
-      #orb_types='DESCENDING'
+      #orb_type='DESCENDING'
       path=/sar/esa.sentinel-1/in-progress/d001/
-      roi_file=${esa_data}/vector/roi_northwest.kml
+      file_roi=${esa_data}/vector/roi_northwest.kml
       ;;
     node6)
-      #orb_types='DESCENDING'
+      #orb_type='DESCENDING'
       path=/sar/esa.sentinel-1/in-progress/d002/
-      roi_file=${esa_data}/vector/roi_whs_20221005.kml
+      file_roi=${esa_data}/vector/roi_whs_20221005.kml
       ;;
     *)
-      echo "[$PROG]ERROR: wrong host ($this_host)!!"
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: wrong DIPP host ($this_host)!!"
+      echo "[$PROG]INFO: for non-DIPP system, use"
+      usage_of_it
       exit 1
       ;;
   esac
-  echo host $this_host orb_types $orb_types
+  echo host $this_host orb_type $orb_type
   #exit
 
 fi
@@ -186,47 +204,49 @@ echo user is $user
 
 ###<<<DIPP
 
+
+if [ "$file_roi" == "" ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no aoi KML file given!!"
+  exit 1
+fi
+if [ ! -s $file_roi ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: aoi KML file not exist ($file_roi)!!"
+  exit 1
+fi
+
 if [ "$path" == "" ]; then
   path=`pwd`
 fi
-
-opath=${path}
-echo $opath
-
-#exit
-if [ ! -d $opath ]; then
-  mkdir -p ${opath}
+if [ ! -d $path ]; then
+  ehco "mkdir -p ${path}"
+  echo "mkdir -p ${path}" | sh
 fi
-#exit
-cd $opath
+cd $path
 pwd
 
-file_lock="${opath}/_tmp_${PROG}.lock"
+file_lock="${path}/_tmp_${PROG}.lock"
 if [ -s $file_lock ]; then
   echo "[$PROG]WARNING: locked by $file_lock!! Quit."
   exit 1
 fi
 
-echo "[$PROG]INFO: downloading data for ROI ($roi_file) at $this_host ..." > $file_lock
+echo "[$PROG]INFO: downloading data for ROI ($file_roi) at $this_host ..." > $file_lock
 #exit
 
-for orb_type in $orb_types; do
+
+if [ "$orb_type" == "" ]; then
+  sh_asf_s1_query -r $file_roi -roi_type polygon -out_file ${file_tmp_py} -weeks $w1 -eweeks $w2
+else
+  sh_asf_s1_query -r $file_roi -roi_type polygon -out_file ${file_tmp_py} -weeks $w1 -eweeks $w2  -orb_type $orb_type
   echo orb_type is $orb_type
-  #sh_asf_s1_query -roi_file $roi_file -roi_type polygon -orb_type $orb_type -out_type KML -out_file ${orb_type}.kml -weeks $w1 -eweeks $w2
-  ##sh_asf_s1_query -roi_file $roi_file -roi_type polygon -out_type KML -out_file ${orb_type}.kml -weeks $w1 -eweeks $w2
+  #sh_asf_s1_query -r $file_roi -roi_type polygon -orb_type $orb_type -out_type KML -out_file ${orb_type}.kml -weeks $w1 -eweeks $w2
+  ##sh_asf_s1_query -r $file_roi -roi_type polygon -out_type KML -out_file ${orb_type}.kml -weeks $w1 -eweeks $w2
+  ##sh_asf_s1_query -r $file_roi -roi_type polygon -out_file ${orb_type}.py -weeks $w1 -eweeks $w2
+fi
 
-
-  sh_asf_s1_query -roi_file $roi_file -roi_type polygon -orb_type $orb_type -out_file ${orb_type}.py -weeks $w1 -eweeks $w2
-  ##sh_asf_s1_query -roi_file $roi_file -roi_type polygon -out_file ${orb_type}.py -weeks $w1 -eweeks $w2
-
-
-  #continue
-  #break
-  #sh_asf_s1_get_slc_py ${orb_type}.py $opath $user
-  sh_asf_s1_get_slc_py -file ${orb_type}.py -opath $opath -ac $file_aria2_conf
-done
+echo "sh_asf_s1_get_slc_py -file ${file_tmp_py} -path $path -ac $file_aria2_conf"
+echo "sh_asf_s1_get_slc_py -file ${file_tmp_py} -path $path -ac $file_aria2_conf" | sh
 
 \rm -f $file_lock
 
- 
- 
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_gnss_correct_insar_vel b/sh/sh_gnss_correct_insar_vel
--- a/sh/sh_gnss_correct_insar_vel
+++ b/sh/sh_gnss_correct_insar_vel
@@ -16,7 +16,7 @@
 # Example:
 #   +
 
-# Algorigthm:
+# Algorithm:
 #   + Modified from GMTSAR's correct_insar_with_gnss.csh script.
 
 # Modifications:
@@ -35,21 +35,38 @@ timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
 path_old=`pwd`
 
 usage_of_it(){
-  echo "[$PROG]HELP: ${PROG} "
-  echo "[$PROG]HELP: e.g.,"
-  echo "[$PROG]HELP:   ${PROG} "
+cat <<eob
+$PROG
+|_Rotate InSAR LOS velocities into GNSS LOS direction.
+|+
+  -output from sh_gnss_vel2los (-g)
+  -InSAR velocity grid (-v)
+|<
+  [-g|-gnss GNSS_VELOCITY_PSVELO]
+    default: wang_shen_2019JB018774_Table.S4.psvelo.los
+  [-v|-vel INSAR_VELOCITY_GRID]
+    default: vel_mask_ll.grd
+  [-N|-m|-model GRDTREND_n_model[+r]]
+    default: 3r
+|e.g.,
+  ${PROG}
+  ${PROG} -N 9r
+(c)iGPS (https://github.com/igps-ftk/)
+eob
 }
 
-if [ $# -lt 2 ]; then
-  usage_of_it
-  #exit 1
-fi
+#if [ $# -lt 2 ]; then
+#  usage_of_it
+#  #exit 1
+#fi
 
-file_vel=vel_mask_ll3.grd 
-file_vel=vel_mask.grd 
+file_vel=vel_mask_ll3.grd
+file_vel=vel_mask.grd
 file_vel=vel_mask_ll.grd
 
 file_gnss_los=Table.S4.psvelo.los
+file_gnss_los=Table.S4.psvelo.los
+file_gnss_los=wang_shen_2019JB018774_Table.S4.psvelo.los
 ofile=
 
 file_prm=master.PRM
@@ -71,7 +88,7 @@ while [ "$1" != "" ]; do
       exit 1
       ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
       usage_of_it
       exit 1
       ;;
@@ -80,12 +97,12 @@ while [ "$1" != "" ]; do
 done
 
 if [ ! -s $file_vel ]; then
-  echo "[$PROG]ERROR: InSAR velocity file not exist ($file_vel)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: InSAR velocity file not exist ($file_vel)!!"
   exit 1
 fi
 
 if [ ! -s $file_gnss_los ]; then
-  echo "[$PROG]ERROR: GNSS (los) file not exist ($file_gnss_los)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: GNSS (los) file not exist ($file_gnss_los)!!"
   exit 1
 fi
 
@@ -167,7 +184,7 @@ file_tmp_insar_gnss_diff_grd="${tmp1%.*}_correction.grd"
 ##
 #  echo "Preparing grid characteristics..."
 ##  downsample the grd-file to make a template for blockmedian and surface
-##  make a sample size of the wavelength/16 
+##  make a sample size of the wavelength/16
 ##
 #   ndx=`echo  $filterw '/' $dx ' / 16' | bc`
 #   ndy=`echo  $filterw '/' $dy ' / 16' | bc`
@@ -178,14 +195,14 @@ file_tmp_insar_gnss_diff_grd="${tmp1%.*}_correction.grd"
 #   ndx2=`echo  $x_inc '*' $ndx | bc `
 #   ndy2=`echo  $y_inc '*' $ndy | bc `
 # echo  ndx2 ndy2 $ndx2, $ndy2
- 
- 
+
+
   echo "gmt grdsample $file_vel  -I$x_inc/$y_inc -Gtmp.grd"
   gmt grdsample $file_vel  -I$x_inc/$y_inc -Gtmp.grd
-  
-  
+
+
   #exit
-  
+
 grep '^ ' $file_gnss_los > $file_tmp_gnss_los
 #cat $file_tmp_gnss_los | awk '{print $4,$5,$7}' > $file_tmp_gnss_lld
 
@@ -194,7 +211,7 @@ cat $file_tmp_gnss_los | awk '{print $1,$2,$7}' > $file_tmp_gnss_lld
 
 #awk '{print $1, $2, $3*(4.0*3.141592653)/(-'$wave'*1000.0) }' < $file_tmp_gnss_lld > $file_tmp_gnss_llrad
 #awk '{print $1, $2, $3 }' < $file_tmp_gnss_lld > $file_tmp_gnss_llrad
-  
+
 cat $file_tmp_gnss_lld | gmt grdtrack -G$file_vel | awk '{print $1,$2,($4-$3)}' | grep -v 'nan' > $file_tmp_insar_gnss_diff
 cat $file_tmp_gnss_lld | gmt grdtrack -G$file_vel | awk '{print $1,$2,$4,$3}' | grep -v 'nan' > $file_tmp_insar_and_gnss
 
@@ -204,14 +221,14 @@ echo "#  now blockmedian and surface the data at this resolution"
 
   #echo "gmt blockmedian $file_tmp_insar_gnss_rad -Rtmp.grd > tmp.rad"
   #gmt blockmedian $file_tmp_insar_gnss_rad -Rtmp.grd > tmp.rad
-  
+
   echo "gmt surface  $file_tmp_insar_gnss_diff -Rtmp.grd -T0.1 -G${file_tmp_insar_gnss_diff}.grd "
-  gmt surface  $file_tmp_insar_gnss_diff -Rtmp.grd -T0.1 -G${file_tmp_insar_gnss_diff}.grd 
-  
-  gmt grdtrend ${file_tmp_insar_gnss_diff}.grd -N${N} -T${file_tmp_insar_gnss_diff_trend} 
-  
+  gmt surface  $file_tmp_insar_gnss_diff -Rtmp.grd -T0.1 -G${file_tmp_insar_gnss_diff}.grd
+
+  gmt grdtrend ${file_tmp_insar_gnss_diff}.grd -N${N} -T${file_tmp_insar_gnss_diff_trend}
+
   gmt grdfilter ${file_tmp_insar_gnss_diff_trend} -Dp -Fg17 -G${file_tmp_insar_gnss_diff_trend_flt}
-  
+
 echo "...using grdsample to upsample the correction grid..."
  incre=`  gmt grdinfo -Cn $file_vel | awk '{printf "%d+n/%d+n \n",$9,$10}' `
 echo "gmt grdsample ${file_tmp_insar_gnss_diff_trend_flt} -I$incre -G$file_tmp_insar_gnss_diff_grd"
@@ -222,11 +239,11 @@ gmt grdsample ${file_tmp_insar_gnss_diff_trend_flt} -I$incre -G$file_tmp_insar_g
 #gmt surface $file_tmp_insar_gnss_rad -R$file_vel -T0.1 -G$file_tmp_insar_gnss_rad_grd
 
 
-  
+
   echo "Correcting the interferogram..."
 #
   echo "gmt grdmath $file_vel $file_tmp_insar_gnss_diff_grd SUB = $ofile "
-  gmt grdmath $file_vel $file_tmp_insar_gnss_diff_grd SUB = $ofile 
+  gmt grdmath $file_vel $file_tmp_insar_gnss_diff_grd SUB = $ofile
 
 
 
@@ -246,7 +263,7 @@ sh_grd2jpg $ofile
 gmt makecpt -Cjet -T-20/20/.1 -I -Z > vel2.cpt
 sh_grd2kml $ofile vel2.cpt
 
-tar zcf gnss.tar.gz *gnss* Table.S4.psvelo.los vel_mask_ll_correction* vel_mask_ll.jpg
+tar zcf gnss.tar.gz *gnss* $file_gnss_los vel_mask_ll_correction* vel_mask_ll.jpg
 
 #clean temporary files
 \rm -rf _tmp_${PROG}_${timestamp}_*
diff --git a/sh/sh_gnss_vel2los b/sh/sh_gnss_vel2los
--- a/sh/sh_gnss_vel2los
+++ b/sh/sh_gnss_vel2los
@@ -19,7 +19,7 @@
 # Example:
 #   +
 
-# Algorigthm:
+# Algorithm:
 #   + Modified from GMTSAR's gnss_enu2los.csh script.
 #   + Only horizontal veloctiies used (ignore vertical rate).
 #   + Use sh_gnss_enu2los for 3d conversion.
@@ -41,15 +41,48 @@ timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
 path_old=`pwd`
 
 usage_of_it(){
-  echo "[$PROG]HELP: ${PROG} "
-  echo "[$PROG]HELP: e.g.,"
-  echo "[$PROG]HELP:   ${PROG} "
+cat <<eob
+${PROG}
+|_ Convert GNSS horizontal (2-d) displacement/velocity to SAR LOS direction.
+  Modified from GMTSAR's gnss_enu2los.csh script.
+  Outside sites are discarded.
+  Only horizontal veloctiies used (ignore vertical rate).
+    Use sh_gnss_enu2los for 3d conversion instead.
+  Run this script in SBAS output directory.
+|+
+  -master.PRM
+  -master.LED
+  -dem.grd
+  -GNSS displacement/velocity file in GMT psvelo format
+    (lon lat vE vN sigE sigN corrEU site)
+  -SAT_look (GMTSAR)
+  -SAT_llt2rat (GMTSAR)
+|<
+  [-d|-dem DEM_FILE]
+    default: dem.grd
+  [-g|-gnss GNSS_VELOCITY_FILE]
+    default: \$iGPS/tables/wang_shen_2019JB018774_Table.S4.psvelo
+  [-m|-master MASTER_PRM]
+    default: master.PRM
+  [-v|-vel SBAS_VEL_FILE]
+    default: vel_mask_ll.grd
+  [-o|-ofile OUTPUT_LOS_VEL_FILE]
+    default: \${GNSS_VELOCITY_FILE}.los
+  [-h|-help|--help]
+|>
+  GNSS velocities file (in LOS direction), e.g.
+  #1_lon 2_lat 3_elevation_m  4_range 5_azimuth 6_elevation_prm  7_disp_los   8_vE 9_vN 10_sigE 11_sigN 12_corrEN 13_site
+   85.456000000 37.387000000 729.162530000 30899.661136889 74913.825499366 795.985317792 -1.637628500000 0.5 12.0 1.2 1.1 0.029 AQIN_GPS
+|e.g.,
+  ${PROG} 
+  ${PROG} -g gnss_horizontal_velocity.psvelo
+eob
 }
 
-if [ $# -lt 2 ]; then
-  usage_of_it
-  #exit 1
-fi
+#if [ $# -lt 2 ]; then
+#  usage_of_it
+#  #exit 1
+#fi
 
 file_vel=vel_mask_ll.grd #for extracting geographical ranges
 
@@ -58,6 +91,7 @@ file_led=
 file_dem=dem.grd
 file_gnss=gnss.psvelo
 file_gnss=$GMT_pub/gps/wang.min.jgr2020/Table.S4.psvelo
+file_gnss=$iGPS/tables/wang_shen_2019JB018774_Table.S4.psvelo
 ofile=
 is_verbose=n
 
@@ -78,6 +112,9 @@ while [ "$1" != "" ]; do
     -v|-vel)
       file_vel=$2
       ;;
+    -o|-ofile)
+      ofile=$2
+      ;;
     -V|-ver|-verbose)
       is_verbose=$2
       shift 1
@@ -88,7 +125,7 @@ while [ "$1" != "" ]; do
       exit 1
       ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
       usage_of_it
       exit 1
       ;;
@@ -97,7 +134,7 @@ while [ "$1" != "" ]; do
 done
 
 if [ ! -s $file_prm ]; then
-  echo "[$PROG]ERROR: master PRM file not exist ($file_prm)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: master PRM file not exist ($file_prm)!!"
   exit 1
 fi
 
@@ -121,7 +158,7 @@ if [ ! -s $file_dem ]; then #try global ETOPO1 model
 fi
 
 if [ ! -s $file_dem ]; then
-  echo "[$PROG]ERROR: DEM file not exist ($file_dem)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: DEM file not exist ($file_dem)!!"
   exit 1
 fi
 
@@ -139,22 +176,22 @@ if [ "$file_led" == "" ]; then
   done
 fi
 if [ ! -s $file_led ]; then
-  echo "[$PROG]ERROR: LED file not exist ($file_led)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: LED file not exist ($file_led)!!"
   exit 1
 fi
 
 
 if [ "$file_gnss" == "" ]; then
-  echo "[$PROG]ERROR: no GNSS file given ($file_gnss)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no GNSS file given ($file_gnss)!!"
   exit 1
 fi
 if [ ! -s $file_gnss ]; then
-  echo "[$PROG]ERROR: GNSS file not exist ($file_gnss)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: GNSS file not exist ($file_gnss)!!"
   exit 1
 fi
 
 if [ ! -s $file_vel ]; then
-  echo "[$PROG]ERROR: InSAR velocity file not exist ($file_vel)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: InSAR velocity file not exist ($file_vel)!!"
   exit 1
 fi
 
diff --git a/sh/sh_s1_prep_f123 b/sh/sh_s1_prep_f123
--- a/sh/sh_s1_prep_f123
+++ b/sh/sh_s1_prep_f123
@@ -2,11 +2,11 @@
 
 # Name:
 #   sh_s1_prep_f123
-#   
+#
 
 # Purpose:
 #   Prepare files for merging F1, F2, and F3 phase grids for running merge_batch.csh
-#   
+#
 #		experiment structure:
 #   EXPT/F1
 #       /F2
@@ -18,34 +18,65 @@
 #			sh_s1_prep_f123
 
 # Modifications:
-#   
+#
 
-# Algorigthm:
-#   
+# Algorithm:
+#
 
 # Dependency:
 #
 
 PROG=sh_s1_prep_f123
-         
-path_comb=`pwd`/f123
 
-#for old asc_F?/des_F? directory structure
-##test ascending/descending
-#orb_type=
-#if [ -d ./asc_F1 ]; then
-#    orb_type=asc
-#elif [ -d ./des_F1 ]; then
-#    orb_type=des
-#else
-#    echo "[]ERROR:no ascending/descending paths found!"
-#    echo exit 1
+timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
+
+path_old=`pwd`
+
+usage_of_it(){
+cat <<eob
+${PROG}
+|_Prepare files for merging F1,F2,F3 phases using merge_batch.csh.
+|+
+  -F1/...
+  -F2/...
+  -F2/...
+  -dem.grd
+  -sh_sar_eof2kml
+  -sh_s1_prep_f123_in
+|<
+  [-h|-help|--help]
+|>
+  f123/...
+|e.g., 
+  ${PROG}
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
+
+#if [ $# -eq 0 ]; then
+#    usage_of_it
+#    exit 1
 #fi
-#
-#echo "orbit type: $orb_type"
 
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
+    *)
+      usage_of_it
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      exit 1
+      ;;
+  esac
+  shift 2
+done
+
+#output path
+path_comb=`pwd`/f123
 echo "[$PROG]INFO: creating output path ($path_comb) ..."
-#echo "mkdir f123.1"
 mkdir -p $path_comb
 mkdir -p $path_comb/topo
 mkdir -p $path_comb/intf_all
@@ -56,7 +87,7 @@ pwd
 
 path_F1=../F1
 if [ ! -d $path_F1 ]; then
-  echo "[]ERROR: $path_F1 not exist!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: $path_F1 not exist!!"
   exit 1
 fi
 
@@ -72,36 +103,35 @@ pwd
 
 
 echo "[$PROG]INFO: linking/copying files ..."
-cd topo 
-rm -rf dem.grd 
-ln -s ../../dem.grd ./ 
-ln -s ../trans.dat ./ 
+cd topo
+rm -rf dem.grd
+ln -s ../../dem.grd ./
+ln -s ../trans.dat ./
 cd ..
 pwd
 ln -s ../dem.grd .
 cp -fp ${path_F1}/intf.in .
 cp -fp ${path_F1}/baseline_table.dat .
 cp -fp ${path_F1}/batch_tops.config ./batch_tops.config.3
-#cp -fp ${path_F1}/3README_sbas1.txt .
 cp -fp ${path_F1}/*.tab1 .
 cp -fp ${path_F1}/data.in .
 cp -fp ${path_F1}/baseline.ps .
 cp -fp ${path_F1}/topo/master.PRM ./topo/
 file_led=`cat ./topo/master.PRM | grep led_file | tail -1 | awk '{print $3}'`
-echo file_led $file_led
+#echo file_led $file_led
 cp -fp ${path_F1}/raw/${file_led} ./topo/
 
 is_snaphu=`cat batch_tops.config.3 | sed '/^ *#/d' | sed '/^$/d' | grep threshold_snaphu | awk '{if($3>0){print 1}else{print 0}}'`
 
 if [ $is_snaphu -eq 0 ]; then
-  sed -e 's/threshold_snaphu \= 0/threshold_snaphu \= 0.01/g' batch_tops.config.3 >batch_tops.config 
+  sed -e 's/threshold_snaphu \= 0/threshold_snaphu \= 0.01/g' batch_tops.config.3 >batch_tops.config
 else
   cp -fp batch_tops.config.3 batch_tops.config
 fi
 pwd
- 
+
 echo "[$PROG]INFO: searching interferograms available for merging_batch ..."
-sh_s1_prep_f123_in 
+sh_s1_prep_f123_in
 
 head -1 baseline_table.dat
 head -1 intf.in.f123.1
diff --git a/sh/sh_s1_unzip b/sh/sh_s1_unzip
--- a/sh/sh_s1_unzip
+++ b/sh/sh_s1_unzip
@@ -13,7 +13,7 @@
 # Modifications:
 #   
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
@@ -27,37 +27,45 @@ timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
 path_old=`pwd`
 
 usage_of_it(){
-  echo "[$PROG]HELP: ${PROG} "
-  echo "[$PROG]HELP:   [-f|-file FRAME_LIST_FILE]"
-  echo "[$PROG]HELP:   [-i|-iw SUBSWATH (default all: iw1,iw2,iw3)]"
-  echo "[$PROG]HELP:   [-p|-path S1_SLC_FILE_PATH]"
-  echo "[$PROG]HELP:   [-u|-update IN_UPDATE_MODE_y_n]"
-
-  echo "[$PROG]HELP:   [-h|-help]"
-  echo "[$PROG]HELP: e.g.,"
-  echo "[$PROG]HELP:   ${PROG} "
+cat <<eob
+${PROG}
+|_Unzip S1 data files to a temporary directory for processing.
+|<
+  -f|-file FRAME_LIST_FILE
+  [-i|-iw SUBSWATH]
+    default: iw1,iw2,iw3
+  [-p|-path S1_SLC_FILE_PATH]
+    default: \${esa_data}/s1/
+  [-o|-opath OUTPUT_PATH]
+    default: \${esa_unzip}/
+  [-u|-update IN_UPDATE_MODE_y_n]
+    Updating from existing processing session (for sh_s1_run_tsa_update)
+  [-h|-help]
+|>
+  OUTPUT_PATH/S1*.SAFE
+|e.g.,
+  ${PROG} -f input.lst.ok -iw iw1
+  ${PROG} -f input.lst.ok.seasonal -iw iw2,iw3
+(c)iGPS (https://github.com/igps-ftk/)
+eob
 }
-
 
 if [ "$1" == "" ]; then
     usage_of_it
     exit 1
 fi
 
-if [ "$esa_unzip" = "" ]; then
-    echo "[$PROG]ERROR: esa_unzip variable not set!!"
-    exit 1
-fi
-
-esa_data_s1=/sar/esa.sentinel-1/alll
-#esa_data_s1=/sar/esa.sentinel-1/links
-esa_data_s1=${esa_data}/s1
-
+path_s1=/sar/esa.sentinel-1/alll
+#path_s1=/sar/esa.sentinel-1/links
+path_s1=${esa_data}/s1
 
 iws="iw1,iw2,iw3"
 
 is_check_done=n
 is_test=n #no uncompressing; only tell whether data exists
+
+opath=`pwd`
+opath=${esa_unzip}
 
 #two modes of input parameters
 if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
@@ -70,11 +78,11 @@ if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
       -i|-iw)
         iws=$2
         ;;
-      -l|-local)
-        is_local=$2
-        ;;
       -p|-path)
-        esa_data_s1=$2
+        path_s1=$2
+        ;;
+      -o|-opath)
+        opath=$2
         ;;
       -t|-test)
         is_test=$2
@@ -87,8 +95,8 @@ if [ "`echo $1 | awk '{print substr($1,1,1)}'`" == "-" ]; then
         exit 1
         ;;
       *)
-        echo "[$PROG]ERROR: invalid option ($1)!!"
         usage_of_it
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
         exit 1
         ;;
     esac
@@ -101,12 +109,17 @@ else  #mode 2
   if [ "$2" != "" ]; then
     iws=$2
   fi
+  if [ "$esa_unzip" = "" ]; then
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: esa_unzip variable not set!!"
+      exit 1
+  else 
+    opath=$esa_unzip
+  fi
   
 fi  #end-of-mode-2
 
 
+echo sh_s1_unzip_node -path $path_s1 -file $file -iw $iws -u $is_check_done -t $is_test -o $opath
+echo sh_s1_unzip_node -path $path_s1 -file $file -iw $iws -u $is_check_done -t $is_test -o $opath | sh
 
-echo sh_s1_unzip_node -path $esa_data_s1 -file $file -iw $iws -u $is_check_done -t $is_test
-echo sh_s1_unzip_node -path $esa_data_s1 -file $file -iw $iws -u $is_check_done -t $is_test | sh
-
-
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_s1_unzip_manifest b/sh/sh_s1_unzip_manifest
--- a/sh/sh_s1_unzip_manifest
+++ b/sh/sh_s1_unzip_manifest
@@ -13,64 +13,86 @@
 # Modifications:
 #
 
-# Algorigthm:
+# Algorithm:
 #
 
 # Dependency:
 #
 PROG=sh_s1_unzip_manifest
 
-#if [ -t 0 ]; then
-#    interactive=1
-#else
-#    interactive=0
-#fi
-##echo "interactive $interactive"
-#
-#if [ $interactive -eq 0 ]; then
-#  . ${HOME}/.bashrc  
-#fi
+path_old=`pwd`
 
-if [ "$esa_data" = "" ]; then
-    echo "[${PROG}]ERROR: ESA environment variable esa_data must be set first! Stopped."
+usage_of_it(){
+cat <<eob
+${PROG}
+|_Extract *.manifest.safe files from Sentinel-1 SLC *.zip file.
+|<
+  [-p|-path INPUT_SLC_PATH]
+    default: current
+  [-o|-opath OUTPUT_PATH]
+    default: current
+|>
+  OUTPUT_PATH/S1*.manifest.safe
+|e.g.,
+  $PROG  -p /sar/s1 -o /sar/manifest.safe/
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
+
+
+#if not called by crontab
+if [ -t 0 ]; then
+  interactive=1
+  
+  path=`pwd`
+  opath=`pwd`
+  
+else
+  interactive=0
+  . ${HOME}/.bashrc
+  if [ "$esa_data" = "" ]; then
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: ESA environment variable esa_data must be set first! Stopped."
+      exit 1
+  fi
+  if [ ! -d $esa_data ]; then
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: esa_data ($esa_data) not exist!!"
     exit 1
-fi
-
-echo "[${PROG}]INFO: Usage: $PROG [out_path  [input_path] ]"
-echo "[${PROG}]INFO:   Default:"
-echo "[${PROG}]INFO:     out_path: ${esa_data}/safe/S1"
-echo "[${PROG}]INFO:     input_path: ${esa_data}/s1"
-
-#opath=${esa_data}/safe/safe
-if [ "$1" == "" ]; then
+  fi
+  
+  path="${esa_data}/s1"
   opath=${esa_data}/safe/S1
   opath=${esa_data}/metainfo/manifest.safe
-else
-  oldopath="`pwd`"
-  mkdir -p $1
-  cd "$1"
-  opath="`pwd`"
-  cd "$oldopath"
 fi
 
-path="${esa_data}/s1"
-if [ "$2" != "" ]; then
-    path_old="`pwd`"
-    cd "$2"
-    path="`pwd`"
-    cd "$path_old"
-fi
 
-echo "[${PROG}]INFO:   Currently:"
-echo "[${PROG}]INFO:     out_path: ${opath}"
-echo "[${PROG}]INFO:     input_path: ${path}"
+while [ "$1" != "" ]; do
+  case $1 in
+    -p|-path)
+      path=$2
+      ;;
+    -o|-opath)
+      opath=$2
+      ;;
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
+    *)
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      usage_of_it
+      exit 1
+      ;;
+  esac
+  shift 2  
+done
+
+echo "[${PROG}]INFO: input path: ${path}"
+echo "[${PROG}]INFO: out path: ${opath}"
 #exit
 
 mkdir -p $opath
-#mkdir -p $opath/all
 
-#files=`ls ${path}/*.zip`
-files=`find "$path" -maxdepth 1 -name "S1*.zip"`
+files=`find "$path" -maxdepth 1 -name "S1*.zip" | sort`
 np=0
 for file in $files; do
     #echo $file
@@ -86,25 +108,12 @@ for file in $files; do
     
     if [ ! -s "$ofile" ]; then
       echo "[${PROG}]WARNING: zero size output file! Deleted."
-      rm -f "$ofile"
+      \rm -f "$ofile"
       continue
-      #mv $file ${esa_data}/S1/tmp/
     fi
-    
-    #track=`grep relativeOrbitNumber $ofile | head -1 | awk -F\< '{print $2}' | awk -F\> '{print $2}'`
-    #ad=`grep pass $ofile | head -1 | awk -F\< '{print $2}' | awk -F\> '{print substr($2,1,1)}'`
-    #echo track $track ad $ad
-    #opath_i=${opath}/${ad}${track}
-    #echo mkdir -p $opath_i
-    #echo mkdir -p $opath_i | sh
-    #echo "\mv -f $ofile $opath_i"
-    #echo "\mv -f $ofile $opath_i" | sh
-    #echo "ln -s ${opath_i}/`basename $ofile` ${opath}/all/"
-    #echo "ln -s ${opath_i}/`basename $ofile` ${opath}/all/" | sh
-    #exit
 
     #exit
     np=`expr $np + 1`
 done
 echo "[${PROG}]INFO: # ${np} manifest.safe files added."
-
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_sar_plot_vel_profile b/sh/sh_sar_plot_vel_profile
--- a/sh/sh_sar_plot_vel_profile
+++ b/sh/sh_sar_plot_vel_profile
@@ -13,7 +13,7 @@
 # Modifications:
 #
 
-# Algorigthm:
+# Algorithm:
 #
 
 # Dependency:
@@ -21,9 +21,44 @@
 
 PROG=sh_sar_plot_vel_profile
 
+
+timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
+
+path_old=`pwd`
+
+usage_of_it(){
+cat <<eob
+${PROG}
+|_Plot velocity profile generated by sar_los_profile_auto.
+|+
+  -p.xxx/profile_???_vel.psxy  
+|<
+  [-p|-path PROFILE_PATH]
+    default: the first p.xxx directory (if present)
+  [-o|-opath OUTPUT_PATH]
+    default: pp.xxx/
+  [-n|-profile PROFILE_IDS]
+    default: 0 (all)
+  [-dt|-data_type Velocity|Dislacement]
+  [-aa|-auto_axis n|y]
+  [-R|-Rp R_OF_TIME_SERIES_PLOT]
+    u - -R-600/600/-20/20
+    ...
+|>
+  -pp.xxx/profile_???_vel.jpg
+|e.g.,
+  $PROG
+  $PROG -p p.fa_atf -o pp.fa_atf_autoaxis -auto_axis y
+  $PROG -n 3,4,8,103
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
+
+
 if [ "$GMT_pub" = "" ]; then
-    echo "[$PROG]ERROR:GMT_pub variable not set!!"
-    exit 1
+    #echo -e "[$PROG]\033[1;33;41mERROR\033[0m:GMT_pub variable not set!!"
+    #exit 1
+    echo "[$PROG]\033[1;33;44mWARNING\033[0m:No DEM map avaiable!"
 fi
 
 
@@ -138,10 +173,10 @@ BP=
 opath_cmt=
 
 while [ "$1" != "" ]; do
-    case $1 in
+  case $1 in
     -p|-path)
         if [ ! -d $2 ]; then
-            echo "[$PROG]ERROR: input directory not exist ($2) !!"
+            echo -e "[$PROG]\033[1;33;41mERROR\033[0m: input directory not exist ($2) !!"
             exit 1
         fi
         cd $2
@@ -163,10 +198,10 @@ while [ "$1" != "" ]; do
     -n|-profile)
         pis=`echo $2 | sed -e 's/,/ /g'`
         ;;
-    -data_type)
+    -dt|-data_type)
         data_type=$2
         ;;
-    -auto_axis)
+    -aa|-auto_axis)
         auto_axis=$2
         opath_cmt='autoAxis'
         ;;
@@ -215,11 +250,15 @@ while [ "$1" != "" ]; do
         icon_Y=`echo $2 $icon_Y | awk '{print $2*$1/7}'`
         icon_w=`echo $2 $icon_w | awk '{print $2*$1/7}'`
         ;;
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
     *)
-        echo "[$PROG]ERROR: invalid option ($1)!!"
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
         echo "[$PROG]Usage: ${PROG} [ -path IN ] [ -opath OUT ] [ -profile 0|n1,n2,n3 ]"
         echo "[$PROG]Usage: e.g.,"
-        echo "[$PROG]Usage: ${PROG} -path p.jiali -opath pp.jiali -profile 3,4,8,103"
+        echo "[$PROG]Usage: ${PROG} -path p.jiali -opath pp.jiali "
         exit 1
         ;;
     esac
@@ -232,7 +271,7 @@ if [ "$profiles_path" == "" ]; then
   #echo path $path
   profiles_path=`find $path_old -maxdepth 1 -type d -name "p.*"|sort|head -1`
   if [ "$profiles_path" == "" ]; then
-    echo "[]ERROR: no input profiles path given!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no input profiles path given!!"
     exit 1
   fi
 fi
@@ -252,7 +291,7 @@ echo opath is $opath
 #exit
 
 if [ ! -d $profiles_path ]; then
-    echo "[$PROG]ERROR: profile path not exist ($profiles_path)!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: profile path not exist ($profiles_path)!!"
     exit 1
 fi
 #pis=51
@@ -484,66 +523,65 @@ for n in $pis; do
 #101.26 37.770 0.6
 #eob
 
-    #micro-seismicity
-    file=/cygdrive/d/ICD/projects/nsfc/2011/annual.report.2
-    file=${GMT_pub}/quake/xqc/pre-1970.txt
-    cat $file | awk '{print $1,$2,$3*.1}' > .tmp
-    file=${GMT_pub}/quake/xqc/post-1970.txt
-    cat $file | awk '{print $1,$2,$3*.1}' >> .tmp
-    #gmt psxy -R -J -h1 -O -K .tmp -Sc -W.35p,purple >> $ofile
+    ##micro-seismicity
+    #file=/cygdrive/d/ICD/projects/nsfc/2011/annual.report.2
+    #file=${GMT_pub}/quake/xqc/pre-1970.txt
+    #cat $file | awk '{print $1,$2,$3*.1}' > .tmp
+    #file=${GMT_pub}/quake/xqc/post-1970.txt
+    #cat $file | awk '{print $1,$2,$3*.1}' >> .tmp
+    ##gmt psxy -R -J -h1 -O -K .tmp -Sc -W.35p,purple >> $ofile
 
     echo "[$PROG]INFO: adding fault lines"
-    #file=./fault/fault_gmt psxy.txt
-    #gmt psxy -R -J -O -K -W.5p,blue -m $file >> $ofile
-    #file=./tibet-fault.txt
-    file=../../faultline/mtab.mif.shp/yarlung-fixed.psxy
-    #gmt psxy -R -J -O -K -W.5p,black -Sf1i/.25+r+s+o.5i -m $file >> $ofile
+    ##file=./fault/fault_gmt psxy.txt
+    ##gmt psxy -R -J -O -K -W.5p,blue -m $file >> $ofile
+    ##file=./tibet-fault.txt
+    #file=../../faultline/mtab.mif.shp/yarlung-fixed.psxy
+    ##gmt psxy -R -J -O -K -W.5p,black -Sf1i/.25+r+s+o.5i -m $file >> $ofile
 
-
-    echo "[$PROG]INFO: dextral faults"
-    file=${GMT_pub}/vector/HimaTibetMap-master/gmt/dextral.gmt
-    gmt psxy -R -J -O -Sf1i/.25+r+s+o.5i -W.25p,blue -K  $file >> $ofile
-    echo "[$PROG]INFO: sinistral faults"
-    file=${GMT_pub}/vector/HimaTibetMap-master/gmt/sinistral.gmt
-    gmt psxy -R -J -O -Sf2i/.25+l+s+o.5i -W.25p,red -K  $file >> $ofile
-    echo "[$PROG]INFO: normal faults"
-    file=${GMT_pub}/vector/HimaTibetMap-master/gmt/normal.gmt
-    #gmt psxy -R -J -O -W.5p,black,- -K  $file >> $ofile
-    gmt psxy -R -J -O -K -Sf.51/.0512+l+b -Gwhite -W.25p,black $file >> $ofile
-    file=${GMT_pub}/vector/HimaTibetMap-master/gmt/thrust.gmt
-    #gmt psxy -R -J -O -W.5p,black,- -K  $file >> $ofile
-    gmt psxy -R -J -O -K -Sf.51/.0512+l+t -Gblack -W.25p,black $file >> $ofile
-
+    if [ -d ${GMT_pub}/vector/HimaTibetMap-master/gmt/ ]; then
+      echo "[$PROG]INFO: dextral faults"
+      file=${GMT_pub}/vector/HimaTibetMap-master/gmt/dextral.gmt
+      gmt psxy -R -J -O -Sf1i/.25+r+s+o.5i -W.25p,blue -K  $file >> $ofile
+      echo "[$PROG]INFO: sinistral faults"
+      file=${GMT_pub}/vector/HimaTibetMap-master/gmt/sinistral.gmt
+      gmt psxy -R -J -O -Sf2i/.25+l+s+o.5i -W.25p,red -K  $file >> $ofile
+      echo "[$PROG]INFO: normal faults"
+      file=${GMT_pub}/vector/HimaTibetMap-master/gmt/normal.gmt
+      #gmt psxy -R -J -O -W.5p,black,- -K  $file >> $ofile
+      gmt psxy -R -J -O -K -Sf.51/.0512+l+b -Gwhite -W.25p,black $file >> $ofile
+      file=${GMT_pub}/vector/HimaTibetMap-master/gmt/thrust.gmt
+      #gmt psxy -R -J -O -W.5p,black,- -K  $file >> $ofile
+      gmt psxy -R -J -O -K -Sf.51/.0512+l+t -Gblack -W.25p,black $file >> $ofile
+    fi
     #file=../gmt.plot/.tmp
     #cat $file | awk '{print $2,$3,$6,$10,$7,$11,$12,substr($1,1,4)}' > .tmp
 
     echo "[$PROG]INFO: adding gps velocity map"
     file=vel.lhasa.2015oct
     file=${GMT_pub}/gps/vel.lhasa.2016jul
-    #file=../../tibet.velrot/vel.tibet_cgps_sgps
-    #*Station   Longitude   Latitude Ve_init Ve_incr    Ve     dVe   Vn_init Vn_incr    Vn     dVn   Cen
-    # AIRA_GPS  130.5996   31.8241   -19.3    15.5   -34.8     0.2    23.2    27.6    -4.4     0.0
-    ##grep "^ " $file | awk '{print $2,$3,$6,$10,$7,$7,0.0,tolower(substr($1,1,4))}' > .tmp.gps
-    grep "^ " $file | awk '{if($11<2&&$7<2){print $2,$3,$6,$10,$7,$11,$12,tolower(substr($1,1,4))}}' > .tmp.gps
-
-    #file=${GMT_pub}/gps/Supp_Table_S1.psvelo
-    #cat $file > .tmp.gps
-
-    #file=${GMT_pub}/gps/velo.psvelo
-    #cat $file > .tmp.gps
-
-    #   113.21    40.79 2.99667 -1.09333 0.13 0.17 A006
-    #file=${GMT_pub}/gps/pingjun.vel
-    #cat $file | awk '{print $1,$2,$3,$4,$5,$6,0,$7}' > .tmp.gps
-
-
-    #file=${GMT_pub}/gps/wang.min.jgr2020/Table.S4
-    #grep '^ ' $file | awk '{print $2,$3,$5,$8,$6,$9,$10,$1}' > .tmp.gps
-
-
-    gmt psxy -R -J -Sc0.12c -W.5p -Gwhite .tmp.gps -O -K -h1 >> $ofile
-    gmt psvelo -R -J -W0.35p,navy -Glightblue -Se.1/0.95/0   -L -A6p+e  .tmp.gps -O -K>> $ofile
-
+    if [ -s $file ]; then
+      #file=../../tibet.velrot/vel.tibet_cgps_sgps
+      #*Station   Longitude   Latitude Ve_init Ve_incr    Ve     dVe   Vn_init Vn_incr    Vn     dVn   Cen
+      # AIRA_GPS  130.5996   31.8241   -19.3    15.5   -34.8     0.2    23.2    27.6    -4.4     0.0
+      ##grep "^ " $file | awk '{print $2,$3,$6,$10,$7,$7,0.0,tolower(substr($1,1,4))}' > .tmp.gps
+      grep "^ " $file | awk '{if($11<2&&$7<2){print $2,$3,$6,$10,$7,$11,$12,tolower(substr($1,1,4))}}' > .tmp.gps
+  
+      #file=${GMT_pub}/gps/Supp_Table_S1.psvelo
+      #cat $file > .tmp.gps
+  
+      #file=${GMT_pub}/gps/velo.psvelo
+      #cat $file > .tmp.gps
+  
+      #   113.21    40.79 2.99667 -1.09333 0.13 0.17 A006
+      #file=${GMT_pub}/gps/pingjun.vel
+      #cat $file | awk '{print $1,$2,$3,$4,$5,$6,0,$7}' > .tmp.gps
+  
+      #file=${GMT_pub}/gps/wang.min.jgr2020/Table.S4
+      #grep '^ ' $file | awk '{print $2,$3,$5,$8,$6,$9,$10,$1}' > .tmp.gps
+  
+      gmt psxy -R -J -Sc0.12c -W.5p -Gwhite .tmp.gps -O -K -h1 >> $ofile
+      gmt psvelo -R -J -W0.35p,navy -Glightblue -Se.1/0.95/0   -L -A6p+e  .tmp.gps -O -K>> $ofile
+    fi
     
 
 if [ "$is_legend_defo" == "y" ]; then
@@ -571,7 +609,7 @@ eob
     file_gps=${profiles_path_gps}/profile_${n}_vel_los.psxy
 
     if [ ! -s $file ]; then
-        echo "[$PROG]ERROR: profile file ($file) not exist!! Skipped."
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: profile file ($file) not exist!! Skipped."
         continue
     fi
 
@@ -1196,9 +1234,10 @@ eob
     #file_icd_icon=${GMT_pub}/vector/icd.gif
     #gmt psimage $file_icd_icon -Dx-.1i/.3i+w1i  -O -K >> $ofile
     file_icd_icon=${GMT_pub}/vector/logo.png
-    #gmt psimage $file_icd_icon -Dx.1i/.9i+w2i  -O -K >> $ofile
-    gmt psimage $file_icd_icon -Dx.1i/${icon_Y}i+w${icon_w}i  -O -K >> $ofile
-
+    if [ -s $file_icd_icon ]; then
+      #gmt psimage $file_icd_icon -Dx.1i/.9i+w2i  -O -K >> $ofile
+      gmt psimage $file_icd_icon -Dx.1i/${icon_Y}i+w${icon_w}i  -O -K >> $ofile
+    fi
     fi #<<icon
     
     
@@ -1217,5 +1256,4 @@ eob
     #exit
 done  #end-of-profile-loop
 
-#echo "[${PROG}]INFO: done :)"
-echo -e "[${PROG}]INFO:\033[1;33;41m done \033[0m\n"
+echo -e "[${PROG}]INFO:\033[1;33;44m done :)\033[0m\n"
diff --git a/sh/sh_sar_sbas b/sh/sh_sar_sbas
--- a/sh/sh_sar_sbas
+++ b/sh/sh_sar_sbas
@@ -13,7 +13,7 @@
 # Modifications:
 #   
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
@@ -21,6 +21,56 @@
 
 PROG=sh_sar_sbas
 
+timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
+
+path_old=`pwd`
+
+usage_of_it(){
+cat <<eob
+$PROG
+|_Call GMTSAR's SBAS
+|+
+  -intf_all/
+  -intf.tab
+  -scene.tab
+  -./topo/master.PRM
+  -dos2unix
+  -sh_sar_plot_intf_tab
+  -proj_ra2ll.csh (GMTSAR)
+  -sh_sar_cal_sat_incidence
+  -sbas
+  -sbas_parallel
+  -sh_grd2kml
+  -sh_sar_sbas_corr_mask
+  -sh_sar_sbas_tar
+  -sh_mail
+  -sh_sar_sbas_disp_mask_ll_resample
+|<
+  [-a|-atm num]
+  [-fix_incidence n|y]
+  [-fix_range n|y]
+  [-i|-ipath INTF_ALL_PATH]
+    default: intf_all/
+  [-m|-multilook 0|1|2|3|4|...]
+    0-guess from intf_all/x/gauss_*
+    1-gauss_100 (4:1 25m )
+    2-gauss_200 (8:2 50m )
+    3-gauss_400 (16:4 100m )
+    4-gauss_800 (32:8 200m )
+  [-o|-opath OUTPUT_PATH]
+    default: SBAS/
+  [-ow|-overwrite n|y]
+  [-prog sbas/sbas_parallel]
+      [-sat SAT|ENVI]
+  [-file_ll_grd grd_ll_filename]
+  [-h|-help|--help]
+e.g.,
+  ${PROG}
+  ${PROG} -a 3
+  ${PROG} -i intf_all_x2 -m 3
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
 
 
 SAT=SAT #ENVI
@@ -56,29 +106,22 @@ file_led=
 
 while [ "$1" != "" ]; do
   case $1 in
-    -h|help)
-      echo "Usage: $PROG -sat SAT|ENVI -file_ll_grd grd_ll_filename  -atm num "
-      echo "                       -opath out_path -overwrite y|n"
-      echo "                       -fix_incidence y|n -fix_range y|n"
-      echo     To skip one parameter, use \'\' as its value.
-      exit 1
-      ;;
     -sat)
       SAT=$2
       ;;
     -file_ll_grd)
       file_ll_grd=$2
       ;;
-    -atm)
+    -a|-atm)
       n_atm=$2
       ;;
-    -ipath)
+    -i|-ipath)
       intf_path=$2
       ;;
-    -opath)
+    -o|-opath)
       out_path=`dirname "$2/test.txt"`
       ;;
-    -overwrite)
+    -ow|-overwrite)
       overwrite=$2
       ;;
     -prog)
@@ -99,8 +142,13 @@ while [ "$1" != "" ]; do
     -file_scene)
       file_scene_tab=$2
       ;;
+    -h|-help|--help|?)
+     usage_of_it
+     exit 1
+     ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      usage_of_it
       exit 1
       ;;
   esac
@@ -114,13 +162,13 @@ file_log="log.`basename $out_path`"
 echo file_log $file_log
 #exit
 
-echo "[$PROG]INFO: cleaning existing output directory if overwrite is y (rm -rf $out_path && mkdir $out_path)"
+#echo "[$PROG]INFO: cleaning existing output directory if overwrite is y (rm -rf $out_path && mkdir $out_path)"
 if [ -d $out_path ]; then
   if [ "$overwrite" == "y" ]; then
-    echo "[$PROG]WARNING: output directory exist and will be overwritten!"
+    echo "[$PROG]WARNING: output directory exist and will be overwritten($out_path)!"
     #rm -rf $out_path
   else
-    echo "[$PROG]WARNING: output directory exist! Stopped."
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: output directory exist ($out_path)!!"
     exit 1
   fi 
 fi
@@ -141,7 +189,7 @@ echo \cp -fp  $file_led $out_path/ | sh
 
 cd ${out_path}
 if [ $? -ne 0 ]; then
-  echo "[$PROG]ERROR: cannot enter SBAS path ($out_path)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: cannot enter SBAS path ($out_path)!!"
   exit 1
 fi
 #
@@ -186,7 +234,7 @@ if [ ! -s ../topo/master.PRM ]; then
   echo "\cp -fp ../intf_all/$pair/supermaster.PRM ../topo/master.PRM" | sh
 fi
 if [ ! -s ../topo/master.PRM ]; then
-  echo "[$PROG]ERROR: topo/master.PRM is missing ($1)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: topo/master.PRM is missing ($1)!!"
   exit 1
 fi
 \cp -fp ../topo/master.PRM .
@@ -194,7 +242,7 @@ fi
 
 files_prm=`ls ../topo/*.PRM | sort`
 if [ $? -ne 0 ]; then
-    echo "[]ERROR: error when searching PRM file!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: error when searching PRM file!!"
     exit 1
 fi
 file_prm=`echo $files_prm | head -1 | awk '{print $1}'`
@@ -212,7 +260,7 @@ if [ ! -s $led_name ]; then
   elif [ -s ../../F1/raw/$led_name ]; then
     \cp -f ../../F1/raw/$led_name .
   else
-    echo "[]ERROR:no LED file found($lef_name)!!"
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m:no LED file found($lef_name)!!"
     #exit 1
   fi
 
@@ -224,7 +272,7 @@ nscen=`cat scene.tab | wc -l`
 
 #fix wavelength to Sentinel-1's. Change it as necessary.
 #if [ ! -s "../topo/master.PRM" ]; then
-#    echo "[$PROG]ERROR: ../topo/master.PRM must exist!!"
+#    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: ../topo/master.PRM must exist!!"
 #    exit 1
 #fi
 #
@@ -238,7 +286,7 @@ if [ "$fix_incidence" != "y" ]; then
   if [ -s ../incidence ]; then
     tmp=`grep ERROR ../incidence`
     if [ "$tmp" != "" ]; then
-        echo "$PROG[]ERROR: invalid incidence angle (incidence)!! Please remove it to obtain a new one automatically."
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid incidence angle (incidence)!! Please remove it to obtain a new one automatically."
         exit 1
         #rm -f ../incidence
     fi
@@ -262,7 +310,7 @@ if [ "$fix_incidence" != "y" ]; then
       incidence=`sh_sar_cal_sat_incidence -sat $SAT -file $file_ll_grd | tail -1`
       tmp=`echo $incidence | grep -i error`
       if [ "$tmp" != "" ]; then
-          echo "ERROR: invalid incidence angle ($incidence)!!"
+          echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid incidence angle ($incidence)!!"
           exit 1
       fi
       echo $incidence > ../incidence
@@ -286,7 +334,7 @@ if [ "$tmp" = "" ]; then
     fi
     echo file_filter $file_filter
     if [ "$file_filter" = "" ]; then
-      echo "[]WARNING: using default filter width : 400"
+      echo "[$PROG]INFO: using default filter width : 400"
       touch gauss_400
     else
       \cp -fp $file_filter .
@@ -306,7 +354,7 @@ if [ "$tmp" = "" ]; then
         touch gauss_800
         ;;
       1)
-        echo "[$PROG]ERROR: invalid multilook optin ($multilook)!!"
+        echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid multilook optin ($multilook)!!"
         exit 1
         ;;
     esac
@@ -315,7 +363,7 @@ fi
 ls -l gauss_*
 ng=`ls gauss_* |wc -l`
 if [ $ng -gt 1 ]; then
-  echo "[$PROG]ERROR: more than 1 gauss_* files exist!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: more than 1 gauss_* files exist!!"
   exit 1
 fi
 
diff --git a/sh/sh_sar_sbas_extract_time_series_lls b/sh/sh_sar_sbas_extract_time_series_lls
--- a/sh/sh_sar_sbas_extract_time_series_lls
+++ b/sh/sh_sar_sbas_extract_time_series_lls
@@ -15,7 +15,7 @@
 #     Fix a bug when data is NaN for some locations.
 #     Added -N option to grdtrack.
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
@@ -25,6 +25,27 @@
 PROG=sh_sar_sbas_extract_time_series_lls
 
 path_old=`pwd`
+
+
+usage_of_it(){
+cat <<eob
+${PROG}
+|_Extract displacement time series for specified locations.
+  Please run this script in SBAS output directory.
+|+
+  -disp_20?????_mask_ll.grd
+|<
+  [-f|-file LL_FILE]
+    format: site_name longitude latitude
+  [-p|-path SBAS_OUTPUT_PATH]
+    default: \`pwd\`
+  [-o|-opath OUTPUT_PATH]
+    default: neu
+  [-h|-help|--help]
+|e.g.,
+  ${PROG} 
+eob
+}
 
 file=
 path=$path_old
@@ -41,11 +62,13 @@ while [ "$1" != "" ]; do
     -o|-opath)
       opath=$2
       ;; 
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
-      echo "[$PROG]Usage: ${PROG} "
-      echo "[$PROG]Usage: e.g.,"
-      echo "[$PROG]Usage: ${PROG} "
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      usage_of_it
       exit 1
       ;;
   esac
@@ -53,13 +76,13 @@ while [ "$1" != "" ]; do
 done
 
 if [ "$file" == "" ]; then
-  echo "[]ERROR: no input file given!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no input file given!!"
   exit 1
 fi
 
 mkdir -p $opath
 if [ $? -ne 0 ]; then
-  echo "[]ERROR: cannot create output path ($opath)!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: cannot create output path ($opath)!!"
   exit 1
 fi
 
@@ -105,4 +128,3 @@ while read sline; do
 done < $file
 
 \rm -f _disp*_mask_ll.grd.lld*
-
diff --git a/sh/sh_slc_cut b/sh/sh_slc_cut
--- a/sh/sh_slc_cut
+++ b/sh/sh_slc_cut
@@ -13,13 +13,35 @@
 # Modifications:
 #   
 
-# Algorigthm:
+# Algorithm:
 #   
 
 # Dependency:
 #   
 
 PROG=sh_slc_cut
+
+
+usage_of_it(){
+cat <<eob
+$PROG
+|_Clip area of interest from aligned SLC files.
+|+
+  -aligned SLC files (F?/raw/S1_*.*)
+  -trans.dat (for converstion between WGS-84 and radar coordiante)
+|<
+  -r|-f|-file POLYGON_KML
+  [-R RADAR_RANGES_IN_GMT_-R_FORM]
+  [-o|-opath OUTPUT_PATH]
+  [-ow|-overwrite WHETHER_OR_NOT_OVERWRITE_EXISTING]
+|>
+  OUTPUT_PATH/S1_*.SLC
+  OUTPUT_PATH/S1_*.LED
+|e.g.,
+  ${PROG} -r mine.kml
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
 
 
 path_old=`pwd`
@@ -32,7 +54,7 @@ is_overwrite=n
 
 while [ "$1" != "" ]; do
   case $1 in
-    -file)
+    -r|-f|-roi|-file)
       cd `dirname $2`
       file_roi="`pwd`/`basename $2`"
       cd $path_old
@@ -40,14 +62,20 @@ while [ "$1" != "" ]; do
     -R)
       region_cut=$2
       ;;
-    -opath)
+    -o|-opath)
       opath=$2
       ;;
-    -overwrite)
+    -ow|-overwrite)
       is_overwrite=$2
       ;;
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
     *)
-      echo "[$PROG]ERROR: invalid option ($1)!!"
+      usage_of_it
+      echo ""
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
       exit 1
       ;;
   esac
@@ -55,7 +83,7 @@ while [ "$1" != "" ]; do
 done
 
 if [ "$file_roi" == "" -a "$region_cut" == "" ]; then
-  echo "[$PROG]ERROR: at least one type of range MUST be given!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: at least one type of range MUST be given!!"
   echo "[$PROG]        1).ROI file (-file roi.kml)"
   echo "[$PROG]        2).rectangular ranges (XMIN/XMAX/YMIN/YMAX)"
   exit 1
@@ -125,3 +153,4 @@ for file in $files ; do
   #exit
 done
 
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_slurm_intf_tops b/sh/sh_slurm_intf_tops
--- a/sh/sh_slurm_intf_tops
+++ b/sh/sh_slurm_intf_tops
@@ -2,24 +2,58 @@
 
 # Name:
 #   sh_slurm_intf_tops
-#   
+#
 
 # Purpose:
 #   Queue gamit tasks to slurmd.
 
 # Example:
-#   
+#
 
 # Modifications:
-#   
+#
 
-# Algorigthm:
-#   
+# Algorithm:
+#
 
 # Dependency:
-#   
-. ${HOME}/.bashrc
+#
+PROG=sh_slurm_intf_tops
 
+timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
+
+usage_of_it(){
+cat <<eob
+$PROG
+|_Submit intf_tops.csh jobs to SLURM.
+|+
+  -files for subswath processing (F1/F2/F3)
+|<
+  [-f|-file intf.in]
+  [-c|-config batch_tops.config]
+  [-d|-delay DELAY_BETWEEN_SUBMITTING_SECONDS]
+  [-o|-overwrite OVERWRITE_EXISTING_SUBMIT]
+  [-n|-nmax_job NUMBER_OF_MAXIMUM_JOBS_TO_SUBMIT]
+|>
+  slurm_intf_tops_*.cmd
+  slurm_intf_tops_*.sh
+|e.g.,
+  ${PROG}
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
+
+#if called by crontab
+if [ -t 0 ]; then
+    interactive=1
+else
+    interactive=0
+    . ${HOME}/.bashrc
+fi
+#echo "interactive $interactive"
+#if [ $interactive -eq 0 ]; then
+#  . ${HOME}/.bashrc
+#fi
 
 #the directory to hold the interferograms, e.g. f123.1
 COMB_DIR=`pwd`
@@ -45,11 +79,11 @@ tmp=`dirname ${COMB_DIR}/test.txt`
 #echo COMB_DIR is $COMB_DIR
 PROC_ID=`dirname ${tmp} | awk -F\/ '{print $NF}'`
 COMB_ID=`basename ${tmp}`
-echo PROC_ID is $PROC_ID
-echo COMB_ID is $COMB_ID
+#echo PROC_ID is $PROC_ID
+#echo COMB_ID is $COMB_ID
 
 
-#gamit processing directory, e.g. 
+#gamit processing directory, e.g.
 PROC_DIR=/home/tianyf/gsar/
 #echo "*Note: the daily processing will be in ${PROC_DIR}/TEMP/"
 
@@ -65,58 +99,70 @@ overwrite=n
 file_intf_in=intf.in
 batch_config=batch_tops.config
 delay=10
+nmax_job=9999
+is_no_delay_when_alloc=y
 
 while [ "$1" != "" ]; do
-    case $1 in
-	-f|-file)
-	    file_intf_in=$2
-	    ;;
-	-c|-config)
-	    batch_config=$2
-	    ;;
-	-d|-delay)
-	    delay=$2
-	    ;;
-	-ndays)
-	    ndays=$2
-	    ;;
-	-orbit)
-	    orbit=$2
-	    ;;
-	-overwrite)
-	    overwrite=$2
-	    ;;
-        -expt)
-            expts=$2
-            expts=`echo $expts | sed -e 's/,/ /g'`
-            ;;
-	*)
-	    echo "[run_rapid]ERROR: invalid options ($1) !!!"
-	    exit 1
-	    ;;
-    esac
-    shift 2
+  case $1 in
+    -f|-file)
+      file_intf_in=$2
+      ;;
+    -c|-config)
+      batch_config=$2
+      ;;
+    -d|-delay)
+      delay=$2
+      ;;
+    -o|-overwrite)
+      overwrite=$2
+      ;;
+    -n|-nmax|-nmax_job)
+      nmax_job=$2
+      ;;
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
+    *)
+      usage_of_it
+      echo ""
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      exit 1
+      ;;
+  esac
+  shift 2
 done
 
+
+#file_intf_in=intf.in
+if [ ! -s $file_intf_in ]; then
+  usage_of_it
+  echo ""
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: input file not exist ($file_intf_in)!!"
+  exit 1
+fi
+
+#batch_config=batch_tops.config
+if [ ! -s $batch_config ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: processing configuation file not exist ($batch_config)!!"
+  exit 1
+fi
+
+is_no_delay_when_alloc=`echo $delay | awk '{if($1<0){print "y"}else{print "n"}}'`
+delay=`echo $delay | awk '{if($1<0){print -1*$1}else{print $1}}'`
+#echo $is_no_delay_when_alloc $delay
 #exit
 
-#test ascending/descending
-#orb_type=
-#if [ -d ../asc_F1 ]; then
-#    orb_type=asc
-#elif [ -d ../des_F1 ]; then
-#    orb_type=des
-#else
-#    echo "[$PROG]ERROR:no ascending/descending paths found!"
-#    exit 1
-#fi
-#
-#echo "orbit type: $orb_type"
 
-
-
-
+n_job=0
+n_skip=0
+n_new=0
 while read line; do
+    if [ $n_job -gt $nmax_job ]; then
+      echo "[$PROG]INFO: maximum number of job reached ($nmax_job)."
+      break
+    fi
+
     date1=`echo $line |awk -F":" '{print $1}'|cut -c 4-11`
     date2=`echo $line |awk -F":" '{print $2}'|cut -c 4-11`
 
@@ -132,7 +178,7 @@ while read line; do
     day2=`echo $date2 | awk '{print substr($1,7,2)}'`
     doyr2=`doy $year2 $mon2 $day2 | head -1 | awk '{printf("%03d", $6-1)}'`
     #echo $year2 $mon2 $day2 $doyr2
- 
+
     out_dir="${year1}${doyr1}_${year2}${doyr2}"
     #pwd
     #echo $out_dir
@@ -140,18 +186,20 @@ while read line; do
     echo "[$PROG]INFO: chekcing ./intf_all/${out_dir}/unwrap_mask.grd ..."
     if [ -s ./intf_all/${out_dir}/unwrap_mask.grd ]; then
       echo "[$PROG]INFO: already done ($out_dir). Skipped."
+      n_skip=`expr $n_skip + 1`
       continue
     fi
 
     echo "[$PROG]INFO: queuing $out_dir ..."
     #continue
-    #exit 
+    #exit
 
     cmdfile=slurm_intf_tops_${date1}_${date2}.cmd
 
     if [ -s "${ARCHIVE_DIR}/${date1}_${date2}/unwrap_mask_ll.png" ]; then
       if [ "$ovewrite" == "n" ]; then
         echo "[$PROG]INFO:output already! Skipped."
+        n_skip=`expr $n_skip + 1`
         continue
       fi
     else
@@ -163,7 +211,7 @@ while read line; do
 
     logfile="slurm_intf_tops_"$date1"_"$date2".log"
      infile="slurm_intf_tops_"$date1"_"$date2".in"
-    
+
     echo $line > $infile
     #cmdfile=slurm_intf_tops_${date1}_${date2}.cmd
     echo "which gmt" > $cmdfile
@@ -172,7 +220,7 @@ while read line; do
     echo "intf_tops.csh $infile $batch_config" >> $cmdfile
 
     #dir_name=`echo $line | awk -F, '{print $1}' | awk -F: '{print $1}' | awk -F"/" '{print $(NF-1)}'`
-    
+
     dir_name="${date1}_${date2}"
     echo dir_name $dir_name
     file_t=${COMB_DIR}/slurm_intf_tops_${dir_name}.sh
@@ -180,7 +228,7 @@ while read line; do
     #
 
     tmp=`date | sed -e 's/ /_/g' | sed -e 's/:/-/g'`
- 
+
 
     echo "#!/bin/sh" > $file_t
     echo "#SBATCH --job-name=${dir_name}-${COMB_ID}-${PROC_ID}" >> $file_t
@@ -228,20 +276,26 @@ while read line; do
     pwd
     #sleep .1
     sbatch $file_t
+    n_new=`expr $n_new + 1`
 
     tmp1=`sinfo | grep intf | grep -i idle`
     tmp2=`sinfo | grep intf | grep -i mix`
     tmp="${tmp1}${tmp2}"
-    echo "tmp1|$tmp1|"
-    echo "tmp2|$tmp2|"
-    echo "tmp|$tmp|"
-    if [ "$tmp" != "" ]; then
+    #echo "tmp1|$tmp1|"
+    #echo "tmp2|$tmp2|"
+    #echo "tmp|$tmp|"
+    if [ "$tmp" != "" -a "$is_no_delay_when_alloc" != "y" -a $delay -gt 0 ]; then
+      echo "[$PROG]INFO:waiting $delay seconds to submit next job ..."
       sleep $delay
-      echo delay is $delay
     fi
     #exit
+
+    n_job=`expr $n_job + 1`
 done < $file_intf_in
 
 
 sinfo
-squeue
+#squeue
+
+echo "[$PROG]INFO: $n_new jobs submitted and $n_skip skipped."
+echo "[$PROG]INFO: done."
diff --git a/sh/sh_slurm_merge_batch b/sh/sh_slurm_merge_batch
--- a/sh/sh_slurm_merge_batch
+++ b/sh/sh_slurm_merge_batch
@@ -1,25 +1,60 @@
 #!/bin/sh
 
 # Name:
-#   run_gamit_qsub
-#   
+#   sh_slurm_merge_batch
+#
 
 # Purpose:
 #   Queue gamit tasks to slurmd.
 
 # Example:
-#   
+#
 
 # Modifications:
-#   
+#
 
-# Algorigthm:
-#   
+# Algorithm:
+#
 
 # Dependency:
-#   
-. ${HOME}/.bashrc
+#
+PROG=sh_slurm_merge_batch
 
+timestamp=`date | sed -e "s/ /_/g" | sed -e "s/:/-/g"`
+
+usage_of_it(){
+cat <<eob
+$PROG
+|_Submit merging-and-unwrapping jobs to SLURM.
+|+
+  -files from sh_s1_prep_f123 (intf.in.f123.1)
+  -file from sh_s1_prep_f123_in (intf.in.f123.2)
+  -merge_batch2.csh
+|<
+  [-m|-master intf.in.f123.1]
+  [-f|-file intf.in.f123.2]
+  [-c|-config batch_tops.config]
+  [-d|-delay DELAY_BETWEEN_SUBMITTING_SECONDS]
+  [-o|-overwrite OVERWRITE_EXISTING_SUBMIT]
+  [-n|-nmax_job NUMBER_OF_MAXIMUM_JOBS_TO_SUBMIT]
+|e.g.,
+  ${PROG}
+  ${PROG} -d 90 -m intf.in.f123.1 -f intf.in.f123.2 -nmax_job 100
+(c)iGPS (https://github.com/igps-ftk/)
+eob
+}
+
+#if called by crontab
+if [ -t 0 ]; then
+    interactive=1
+else
+    interactive=0
+    . ${HOME}/.bashrc
+fi
+#echo "interactive $interactive"
+#if [ $interactive -eq 0 ]; then
+#  . ${HOME}/.bashrc
+#fi
 
 #the directory to hold the interferograms, e.g. f123.1
 COMB_DIR=`pwd`
@@ -38,7 +73,7 @@ ROOT_DIR=${COMB_DIR}/..
 # |  |-intf_all/
 # |  |-raw/
 # |
-# |-f123/ (running directory)
+# |-f123/ (merging directory)
 # |  |-batch_tops.config
 # |  |-dem.grd
 # |  |-intf.in.f123
@@ -47,7 +82,7 @@ ROOT_DIR=${COMB_DIR}/..
 # |  |-trans.dat
 
 if [ ! -s dem.grd ]; then
-  echo "[$PROG]ERROR: no/wrong dem.grd file!!"
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: no/wrong dem.grd file!!"
   exit 1
 fi
 
@@ -60,7 +95,7 @@ PROC_ID=`dirname ${tmp} | awk -F\/ '{print $NF}'`
 echo PROC_ID is $PROC_ID
 
 
-#gamit processing directory, e.g. 
+#gamit processing directory, e.g.
 PROC_DIR=/home/tianyf/gsar/
 echo "*Note: the daily processing will be in ${PROC_DIR}/temp/"
 
@@ -80,62 +115,64 @@ delay=30
 nmax_job=9999
 
 while [ "$1" != "" ]; do
-    case $1 in
-	-f|-file)
-	    file_intf_in=$2
-	    ;;
-	-m|-master)
-            file_master=$2
-	    ;;
-	-c|-config)
-	    batch_config=$2
-	    ;;
-	-d|-delay)
-	    delay=$2
-	    ;;
-	-ndays)
-	    ndays=$2
-	    ;;
-	-orbit)
-	    orbit=$2
-	    ;;
-	-overwrite)
-	    overwrite=$2
-	    ;;
-        -expt)
-            expts=$2
-            expts=`echo $expts | sed -e 's/,/ /g'`
-            ;;
-        -nmax_job)
-            nmax_job=$2
-            ;;
-	*)
-	    echo "[run_rapid]ERROR: invalid options ($1) !!!"
-	    exit 1
-	    ;;
-    esac
-    shift 2
+  case $1 in
+    -f|-file)
+      file_intf_in=$2
+      ;;
+    -m|-master)
+      file_master=$2
+      ;;
+    -c|-config)
+      batch_config=$2
+      ;;
+    -d|-delay)
+      delay=$2
+      ;;
+    -o|-overwrite)
+      overwrite=$2
+      ;;
+    -n|-nmax|-nmax_job)
+      nmax_job=$2
+      ;;
+    -h|-help|--help)
+      usage_of_it
+      exit 1
+      ;;
+    *)
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      usage_of_it
+      ;;
+  esac
+  shift 2
 done
 
-echo Year/Doy/Ndays/Orbit $year $doyr $ndays $orbit
 #exit
 
-#test ascending/descending
-orb_type=
-if [ -d ../asc_F1 ]; then
-    orb_type=asc
-elif [ -d ../des_F1 ]; then
-    orb_type=des
-else
-    echo "[$PROG]ERROR:no ascending/descending paths found!"
-    #exit 1
+#file_master=intf.in.f123.1
+if [ ! -s $file_master ]; then
+  usage_of_it
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: master file not exist ($file_master)!!"
+  echo "[$PROG]HELP: use sh_s1_prep_f123_in to create input files."
+  exit 1
 fi
 
-echo "orbit type: $orb_type"
+#file_intf_in=intf.in.f123.2
+if [ ! -s $file_intf_in ]; then
+  usage_of_it
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: input file not exist ($file_intf_in)!!"
+  echo "[$PROG]HELP: use sh_s1_prep_f123_in to create input files."
+  exit 1
+fi
 
-
+#batch_config=batch_tops.config
+if [ ! -s $batch_config ]; then
+  echo -e "[$PROG]\033[1;33;41mERROR\033[0m: processing configuation file not exist ($batch_config)!!"
+  exit 1
+fi
 
 n_job=0
+n_skip=0
+n_new=0
 while read line; do
     if [ $n_job -gt $nmax_job ]; then
       echo "[$PROG]INFO: maximum number of job reached ($nmax_job)."
@@ -154,6 +191,7 @@ while read line; do
       echo overwrite $overwrite
       if [ "$overwrite" == "n" ]; then
         echo "[$PROG]INFO:output already exist (${dir_name})! Skipped."
+        n_skip=`expr $n_skip + 1`
         continue
       else
         echo "[$PROG]INFO: >$overwrite<"
@@ -161,13 +199,14 @@ while read line; do
     else
       if [ -s "$cmdfile" -a "$overwrite" == "n" ]; then
         echo "[$PROG]INFO:already queued(${date1}_${date2})! Skipped."
+        n_skip=`expr $n_skip + 1`
         continue
       fi
     fi
 
     logfile="slurm_merge_batch_"$date1"_"$date2".log"
     infile="slurm_merge_batch_"$date1"_"$date2".in"
-    
+
     echo $line > $infile
     #cmdfile=merge_batch_${date1}_${date2}.cmd
     echo "#!/bin/sh" > $cmdfile
@@ -183,7 +222,7 @@ while read line; do
     #
 
     tmp=`date | sed -e 's/ /_/g' | sed -e 's/:/-/g'`
- 
+
 
     echo "#!/bin/sh" > $file_t
     echo "#SBATCH --job-name=${dir_name}-${COMB_ID}-${PROC_ID}" >> $file_t
@@ -233,12 +272,18 @@ while read line; do
     pwd
     #sleep 1
     sbatch $file_t
+    n_new=`expr $n_new + 1`
+
+    echo "[$PROG]INFO:waiting $delay seconds to submit next job ..."
     sleep $delay
-    echo delay is $delay
+
     n_job=`expr $n_job + 1`
     #exit
 done < $file_intf_in
 
 
+#squeue
 sinfo
-squeue
+
+echo "[$PROG]INFO: $n_new jobs submitted and $n_skip skipped."
+echo "[$PROG]INFO: done."
