update 20241105

diff --git a/sh/sh_gnss_vel2los b/sh/sh_gnss_vel2los
--- a/sh/sh_gnss_vel2los
+++ b/sh/sh_gnss_vel2los
@@ -94,6 +94,7 @@ file_dem=dem.grd
 file_gnss=${iGPS}/tables/wang_shen_2019JB018774_Table.S4S5.psvelo
 ofile=
 is_verbose=n
+input_fmt=psvelo #psvelo/psvelou/gps_prd
 
 while [ "$1" != "" ]; do
   case $1 in
@@ -102,6 +103,9 @@ while [ "$1" != "" ]; do
       ;;
     -g|-gnss)
       file_gnss=$2
+      ;;
+    -if|-input_fmt)
+      input_fmt=$2
       ;;
     -l|-led)
       file_led=$2
@@ -116,7 +120,7 @@ while [ "$1" != "" ]; do
       ofile=$2
       ;;
     -V|-ver|-verbose)
-      is_verbose=$2
+      is_verbose=y
       shift 1
       continue
       ;;
@@ -223,7 +227,7 @@ fi
 echo "[$PROG]INFO: file_prm $file_prm"
 echo "[$PROG]INFO: file_led $file_led"
 echo "[$PROG]INFO: file_dem $file_dem"
-echo "[$PROG]INFO: file_gnss $file_gnss"
+echo "[$PROG]INFO: file_gnss ($input_fmt) $file_gnss"
 
 
 
@@ -242,7 +246,22 @@ file_tmp_rrhll=_tmp_${PROG}_${timestamp}_rrhll
 cat $file_gnss | awk '{print $1,$2}' | gmt grdtrack -G$file_vel -N > $file_tmp_llh
 paste $file_tmp_llh $file_gnss > $file_tmp_llh_all
 cat $file_tmp_llh_all | grep -iv nan | awk '{print $1,$2}' | gmt grdtrack -G$file_dem -N > $file_tmp_llh
-cat $file_tmp_llh_all | grep -iv nan | awk '{print $4,$5,$6,$7,$8,$9,$10,$11}' > $file_tmp_gnss
+case $input_fmt in
+  psvelo)
+    cat $file_tmp_llh_all | grep -iv nan | awk '{print $4,$5,$6,$7,$8,$9,$10,$11,0}' > $file_tmp_gnss
+    ;;
+  psvelou)
+    cat $file_tmp_llh_all | grep -iv nan | awk '{print $4,$5,$6,$7,$8,$9,$10,$11,$12}' > $file_tmp_gnss
+    ;;
+  gps_prd)
+    #   long      lat       Ve      dVe       Vn      dVn       Vu      dVn    Tau_h   Tau_v
+    #   88.000   25.500  10.9798   0.8712  23.4754   0.8247  -4.4014   8.8053  70.0000  95.0000
+    cat $file_tmp_llh_all | grep -iv nan | awk '{printf("%8.3f %7.3f  %8.4f %8.4f  %8.4f %8.4f %6.3f %04d_GHI %8.4f\n", $4,$5,$6,$8,$7,$9,.01,NR,$10)}'  > $file_tmp_gnss
+    ;;
+  *)
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: wrong gnss velocity file format ($input_fmt)!!"
+    exit 1
+esac
 #exit
 
 
@@ -257,14 +276,14 @@ SAT_look $file_prm < $file_tmp_llh > $file_tmp_look
 
 # perform the dot product with enu displacements and enu look direction
 # This creates tmp.lltd which is lon | lat | dem height | LOS
-paste $file_tmp_gnss $file_tmp_look | awk '{if ($11 != nan) printf("%.9f %.9f %.9f %.12f\n",$1,$2,$11, ($3*$12)+($4*$13)+(0*$14))}' > $file_tmp_llhd
+paste $file_tmp_gnss $file_tmp_look | awk '{if ($11 != nan) printf("%.9f %.9f %.9f %.12f\n",$1,$2,$12, ($3*$13)+($4*$14)+($9*$15))}' > $file_tmp_llhd
 
 #get radar coordiantes of gnss sites
 SAT_llt2rat $file_prm 1 < $file_tmp_llh > $file_tmp_rrhll
 
 #echo "" | awk '{printf("#%15s %15s %17s  %20s %20s %17s  %15s \n","lon","lat","elevation(m)","range","azimuth","elev_prm", "disp_los")}' > $ofile  
-echo "" | awk '{printf("#%s %s %s  %s %s %s  %s   %s %s %s %s %s %s\n","1_lon","2_lat","3_elevation_m","4_range","5_azimuth","6_elevation_prm", "7_disp_los","8_vE","9_vN","10_sigE","11_sigN","12_corrEN","13_site")}' > $ofile  
-paste $file_tmp_rrhll $file_tmp_llhd $file_tmp_gnss | awk '{print "",$4,$5,$8,$1,$2,$3,$9,$12,$13,$14,$15,$16,$17}' >> $ofile
+echo "" | awk '{printf("#%s %s %s  %s %s %s  %s   %s %s %s %s %s %s %s\n","1_lon","2_lat","3_elevation_m","4_range","5_azimuth","6_elevation_prm", "7_disp_los","8_vE","9_vN","10_sigE","11_sigN","12_corrEN","13_site","14_vU")}' > $ofile  
+paste $file_tmp_rrhll $file_tmp_llhd $file_tmp_gnss | awk '{print "",$4,$5,$8,$1,$2,$3,$9,$12,$13,$14,$15,$16,$17,$18}' >> $ofile
 
 #clean temporary files
 if [ "$is_verbose" == "n" ]; then
diff --git a/sh/sh_sar_plot_intf_in b/sh/sh_sar_plot_intf_in
--- a/sh/sh_sar_plot_intf_in
+++ b/sh/sh_sar_plot_intf_in
@@ -18,6 +18,9 @@
 
 # Dependency:
 #   
+
+PROG=sh_sar_plot_intf_in
+
 gmtset PS_MEDIA = a4
 gmtset FONT_TITLE = 12p
 gmtset FONT_LABEL         = 8p
@@ -40,18 +43,34 @@ fi
 #file intf.tab
 
 
-if [ "$1" = "-h" ]; then
-    echo "Usage: sh_envisat_link_raw [intf.in/align.in]"
-    exit 1
-fi
-
 file=intf.in
-if [ "$1" != "" ]; then
-    file=$1
-fi
-
-
 ofile=f-baseline-time.ps
+is_lbl=n
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -f|-in|-file)
+      file=$2
+      ;;
+    -h|help)
+      echo "Usage: $PROG  [ -out OUTPUT_FILE_BASE_NAME ] [-l|-label y/n] "
+      exit 1
+      ;;
+    -o|-out|-ofile)
+      ofile=$2
+      ;;
+    -l|-label)
+      is_lbl=$2
+      ;;
+    *)
+      echo -e "[$PROG]\033[1;33;41mERROR\033[0m: invalid option ($1)!!"
+      exit 1
+      ;;
+  esac
+
+  shift 2
+done
+
 
 #read baseline_table.dat file
 ids=`cat baseline_table.dat | awk '{print $1}'`
@@ -103,17 +122,20 @@ psxy $R -JX5i/4i -Sc.1c -Gyellow -W.35p,red -B1f.5:"Time":/200f100:"Distance (m)
 psxy -R -J -W0.2p,purple,- -O -K .tmp_  >> $ofile
 
 
-rm -rf .tmp_2
-while read line; do
-  id=`echo $line | awk '{print $1}'`
-  year=`echo $line | awk '{print substr($2,1,4)}'`
-  doyr=`echo $line | awk '{print substr($2,5,3)}'`
-  blen=`echo $line | awk '{print $5}'`
-  dyr=`doy $year $doyr | tail -1 | awk '{print $3}'`
-  echo "$dyr $blen $id" >> .tmp_2
-done < baseline_table.dat
-#
-pstext -R -J -F+f5p+a0+j1 -O -K .tmp_2 >> $ofile
+#add text label to observations
+if [ "$is_lbl" == "y" ]; then
+  rm -rf .tmp_2
+  while read line; do
+    id=`echo $line | awk '{print $1}'`
+    year=`echo $line | awk '{print substr($2,1,4)}'`
+    doyr=`echo $line | awk '{print substr($2,5,3)}'`
+    blen=`echo $line | awk '{print $5}'`
+    dyr=`doy $year $doyr | tail -1 | awk '{print $3}'`
+    echo "$dyr $blen $id" >> .tmp_2
+  done < baseline_table.dat
+  #
+  gmt pstext -R -J -F+f5p+a0+j1 -O -K .tmp_2 >> $ofile
+fi
 
 psxy -R -J -O <<eof -W1p,red,- >> $ofile
 >
diff --git a/sh/sh_sar_plot_vel_profile b/sh/sh_sar_plot_vel_profile
--- a/sh/sh_sar_plot_vel_profile
+++ b/sh/sh_sar_plot_vel_profile
@@ -38,6 +38,7 @@ ${PROG}
     default: the first p.xxx directory (if present)
   [-o|-opath OUTPUT_PATH]
     default: pp.xxx/
+  [-c|-comment COMMENTS]
   [-n|-profile PROFILE_IDS]
     default: 0 (all)
   [-dt|-data_type Velocity|Dislacement]
@@ -189,6 +190,8 @@ mdl_type= #far-field/fault_name/near-field/...
 
 file_gnss=${iGPS}/tables/wang_shen_2019JB018774_Table.S4S5.psvelo
 
+input_fmt=psvelo #psvelo/psvelou/gps_prd
+
 opath_cmt=
 
 while [ "$1" != "" ]; do
@@ -214,6 +217,9 @@ while [ "$1" != "" ]; do
         #cd $path_old
         opath=$2
         ;;
+    -c|-comment)
+      opath_cmt="${opath_cmt}$2"
+      ;;
     -n|-profile)
         pis=`echo $2 | sed -e 's/,/ /g'`
         ;;
@@ -278,7 +284,9 @@ while [ "$1" != "" ]; do
     -g|-gnss|-gnss_file|-gnss_vel)
       file_gnss=$2
       ;;
-
+    -if|-input_fmt)
+      input_fmt=$2
+      ;;
     -h|-help|--help)
       usage_of_it
       exit 1
@@ -622,8 +630,20 @@ for n in $pis; do
       ##grep "^ " $file | awk '{print $2,$3,$6,$10,$7,$7,0.0,tolower(substr($1,1,4))}' > .tmp.gps
       #grep "^ " $file_gnss | awk '{if($11<2&&$7<2){print $2,$3,$6,$10,$7,$11,$12,tolower(substr($1,1,4))}}' > .tmp.gps
   
-      #file=${GMT_pub}/gps/Supp_Table_S1.psvelo
-      cat $file_gnss | shuf | head -100 |sort > .tmp.gps
+case $input_fmt in
+  psvelo|psvelou)
+    #file=${GMT_pub}/gps/Supp_Table_S1.psvelo
+    cat $file_gnss | shuf | head -500 |sort > .tmp.gps
+    ;;
+  gps_prd)
+    #   long      lat       Ve      dVe       Vn      dVn       Vu      dVn    Tau_h   Tau_v
+    #   88.000   25.500  10.9798   0.8712  23.4754   0.8247  -4.4014   8.8053  70.0000  95.0000
+    cat $file_gnss | grep -iv nan | shuf | head -500 |sort |awk '{printf("%8.3f %7.3f  %8.4f %8.4f  %8.4f %8.4f %6.3f %04d_GHI\n", $1,$2,$3,$5,$4,$6,.01,NR)}'  > .tmp.gps
+    ;;
+  *)
+    echo -e "[$PROG]\033[1;33;41mERROR\033[0m: wrong gnss velocity file format ($input_fmt)!!"
+    exit 1
+esac
   
       #file=${GMT_pub}/gps/velo.psvelo
       #cat $file > .tmp.gps
@@ -1068,7 +1088,7 @@ fi
     #echo "**lat of intersect of fault and profile: $lat_fp "
 
     echo "[$PROG]INFO: plot overview map"
-    gmtset MAP_FRAME_TYPE                  = plain
+    gmt gmtset MAP_FRAME_TYPE                  = plain
     gmt gmtset FONT_TITLE = 7p
     gmt gmtset FONT_LABEL         = 6p
     gmt gmtset FONT_ANNOT_PRIMARY = 6p
@@ -1081,13 +1101,13 @@ fi
     #Plot overview inset
     if [ -s $dem_file_overview ]; then
       #grdimage $Ro $Jo  -B10f5/10f5WSEN $dem_file_overview -Cmytopo2.cpt -A250 -K -V -O  >> $ofile
-      grdimage $dem_file_overview  -Cmytopo2.cpt $Ro -JQ${Jo}i    -B10f5:"":/10f5:""::."":EN -K -O >> ${ofile}
+      gmt grdimage $dem_file_overview  -Cmytopo2.cpt $Ro -JQ${Jo}i    -B10f5:"":/10f5:""::."":EN -K -O >> ${ofile}
     else
-      pscoast $Ro -JQ${Jo}i -B10f5:"":/10f5:""::."":EN -K -O -Wthin -I1 -Swhite >> $ofile
+      gmt pscoast $Ro -JQ${Jo}i -B10f5:"":/10f5:""::."":EN -K -O -Wthin -I1 -Swhite >> $ofile
     fi
     #pscoast $R $J -Wthin -I1 -B10f5/10f5WSEN -Glightgray -Wthinnest,lightgray -A250 -K -V -O >> $ofile
     #pscoast $R $J -Wthin -I1 -B10f5/10f5WSEN -Glightgray -Wthinnest,lightgray -A250 -K -V -O >> $ofile
-    psxy -R -J -O -K -L <<eob -Gblue@80 >> $ofile
+    gmt psxy -R -J -O -K -L <<eob -Gblue@80 >> $ofile
     $X_MIN $Y_MAX
     $X_MAX $Y_MAX
     $X_MAX $Y_MIN
@@ -1169,6 +1189,8 @@ eob
     grep "^ " $file | awk '{print $13,$di,$4,$ei}' di=$data_index ei=sigma_index >.tmp.los
     if [ -s $file_mdl ]; then
       grep "^ " $file_mdl | awk '{print $1,$2}' >.tmp.los.mdl
+    else
+      \rm -f .tmp.los.mdl
     fi
 
     if [ "$auto_axis" == "y" ]; then
@@ -1223,7 +1245,7 @@ eob
     echo Bx By $Bx $By
     echo Rp $Rp
     gmt psxy $Rp -JX${plot_size_ax}i/${plot_size_by}i -X${Xshift}i -Y${Yshift}i -Sc0.05c   -B${Bx}:"${profile_title_x}":/${By}:"${profile_title_y}"::."${profile_title}":/SWen -O -K   .tmp.los -Cdist.cpt >>$ofile
-    if [ -s .tmp.los.mdl ]; then
+    if [ -s $file_mdl -a -s .tmp.los.mdl ]; then
       gmt psxy -R -J -O -K .tmp.los.mdl -W1p,red >> $ofile
     fi
 
