update 2023-03-31

diff --git a/sh/sh_s1_prep_proc_baseline b/sh/sh_s1_prep_proc_baseline
--- a/sh/sh_s1_prep_proc_baseline
+++ b/sh/sh_s1_prep_proc_baseline
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Name:
-#   sh_esa_s1_prep_proc_baseline
+#   sh_s1_prep_proc_baseline
 #   
 
 # Purpose:
@@ -17,12 +17,12 @@
 #   
 
 # Dependency:
-#   
+#   + baseline_table.dat
 
-PROG=sh_esa_s1_prep_proc_baseline
+PROG=sh_s1_prep_proc_baseline
 
 
-if [ "$1" == "" -o "$2" == "" ]; then
+function usage_of_it(){
     echo "Usage: $PROG -file baseline_table.dat "
     echo "         -t1|-min_interval min_temporal_baseline"
     echo "         -t2|-max_interval max_temporal_baseline"
@@ -30,7 +30,7 @@ if [ "$1" == "" -o "$2" == "" ]; then
     echo "         -o|-ofile OUT_FILE"
     echo "         -v|-verbose Y_or_N"
     #exit 1
-fi
+}
 
 
 file=baseline_table.dat  #input file
@@ -40,7 +40,7 @@ min_interval=.1 #days
 max_interval=10000 #days
 echo defaults values initiated
 
-update_config=y	#update master line in batch_tops.config with the template (batch_tops.config.2)
+update_config=y #update master line in batch_tops.config with the template (batch_tops.config.2)
 
 ofile=intf.in
 
@@ -48,40 +48,49 @@ is_verbose=n
 
 while [ "$1" != "" ]; 
 do
-    case $1 in
-	-f|-file)
-	    file=`pwd`/$2
-	    ;;
-	-super_master)
-	    super_master_ind=$2
-	    ;;
-	-max_dist)
-	    max_dist=$2
-	    ;;
-        -o|-ofile)
-            ofile=$2
-            ;;
-	-t1|-min_interval)
-	    min_interval=$2
-	    ;;
-        -t2|-max_interval)
-            max_interval=$2
-            ;;
-	-u|-update_config)
-	    update_config=$2
-	    ;;
-        -v|-verbose)
-            is_verbose=$2
-            ;;
-	*)
-	    echo "[$PROG]ERROR: wrong input option ($1)!!"
-	    exit 1
-	    ;;
+  case $1 in
+    -f|-file)
+      file=`pwd`/$2
+      ;;
+    -super_master)
+      super_master_ind=$2
+      ;;
+    -max_dist)
+      max_dist=$2
+      ;;
+    -o|-ofile)
+      ofile=$2
+      ;;
+    -t1|-min_interval)
+      min_interval=$2
+      ;;
+    -t2|-max_interval)
+      max_interval=$2
+      ;;
+    -u|-update_config)
+      update_config=$2
+      ;;
+    -v|-verbose)
+      is_verbose=$2
+      ;;
+    -h)
+      usage_of_it
+      exit 1
+      ;;
+    *)
+      echo "[$PROG]ERROR: wrong input option ($1)!!"
+      usage_of_it
+      exit 1
+      ;;
     esac
     shift 2
 done
 
 
+if [ ! -s $file ]; then
+  echo "[$PROG]ERROR: $file not exist!!"
+  exit 1
+fi
 echo $file
 #exit
 ids=`cat $file | awk '{print $1}'`
@@ -96,38 +105,38 @@ i=1
 while [ $i -le $nday ]; do
     j=`expr $i + 1`
     while [ $j -le $nday ]; do
-	#Remove large perpendicular baseline pairs
-	dist=`echo $dists | awk '{print sqrt(($i-$j)*($i-$j)) }' i=$i j=$j`
-	isOK=`echo $dist $max_dist | awk '{if($1<=$2){print 1}else{print 0}}'`
-	if [ $isOK -ne 1 ]; then
-	    img1=`echo $ids | awk '{print $i}' i=$i`
-	    img2=`echo $ids | awk '{print $j}' j=$j`
+  #Remove large perpendicular baseline pairs
+  dist=`echo $dists | awk '{print sqrt(($i-$j)*($i-$j)) }' i=$i j=$j`
+  isOK=`echo $dist $max_dist | awk '{if($1<=$2){print 1}else{print 0}}'`
+  if [ $isOK -ne 1 ]; then
+      img1=`echo $ids | awk '{print $i}' i=$i`
+      img2=`echo $ids | awk '{print $j}' j=$j`
             if [ "$is_verbose" == "y" ]; then
-  	      echo "[$PROG]INFO:large distance ($dist meters) between $img1 and $img2. Skipped!"
+          echo "[$PROG]INFO:large distance ($dist meters) between $img1 and $img2. Skipped!"
             fi
-	    j=`expr $j + 1`
-	    continue
-	fi
-	#
-	#Remove long temporal interval
-	interval=`echo $doyrs | awk '{print sqrt(($i-$j)*($i-$j)) }' i=$i j=$j`
-	isOK=`echo $interval $min_interval $max_interval | awk '{if($1>=$2&&$1<=$3){print 1}else{print 0}}'`
-	if [ $isOK -ne 1 ]; then
-	    img1=`echo $ids | awk '{print $i}' i=$i`
-	    img2=`echo $ids | awk '{print $j}' j=$j`
+      j=`expr $j + 1`
+      continue
+  fi
+  #
+  #Remove long temporal interval
+  interval=`echo $doyrs | awk '{print sqrt(($i-$j)*($i-$j)) }' i=$i j=$j`
+  isOK=`echo $interval $min_interval $max_interval | awk '{if($1>=$2&&$1<=$3){print 1}else{print 0}}'`
+  if [ $isOK -ne 1 ]; then
+      img1=`echo $ids | awk '{print $i}' i=$i`
+      img2=`echo $ids | awk '{print $j}' j=$j`
             if [ "$is_verbose" == "y"  ]; then
-	      echo "[$PROG]INFO:too short/long time interval ($interval days) between $img1 and $img2. Skipped!"
+        echo "[$PROG]INFO:too short/long time interval ($interval days) between $img1 and $img2. Skipped!"
             fi
-	    j=`expr $j + 1`
-	    continue
-	fi
-	#
-	if [ $super_master_ind -eq 1 ]; then
-	    echo $ids | awk '{print $i":"$j}' i=$i j=$j >> $ofile
-	else
-	    echo $ids | awk '{print $i":"$j":"$smi}' i=$i j=$j smi=$super_master_ind >> $ofile
-	fi
-	j=`expr $j + 1`
+      j=`expr $j + 1`
+      continue
+  fi
+  #
+  if [ $super_master_ind -eq 1 ]; then
+      echo $ids | awk '{print $i":"$j}' i=$i j=$j >> $ofile
+  else
+      echo $ids | awk '{print $i":"$j":"$smi}' i=$i j=$j smi=$super_master_ind >> $ofile
+  fi
+  j=`expr $j + 1`
     done
     i=`expr $i + 1`
 done
